- .travis.yml
- Makefile
- karapace/karapace.py
- karapace/master_coordinator.py
- karapace/rapu.py
- tests/conftest.py
- tests/test_schema.py
Fixes the failing Travis build.
> Fix travis build

- .travis.yml
- dependencies/Makefile
- dependencies/python3-aiohttp_socks/.gitignore
- dependencies/python3-aiohttp_socks/Makefile
- dependencies/python3-aiosocksy/.gitignore
- karapace.spec
- karapace/rapu.py
To be honest I am not certain aiosocksy is even used in karapace, but since aiosocksy is not maintained we should try to migrate away from it.
> deps: Move from deprecated aiosocksy to aiohttp_socks library.

- Makefile
Instead of having to update it manually.
> makefile: make git short version dynamic

- karapace/karapace.py
Additionally transforms the main function to use argparse.
> karapace: add --version command

- karapace/rapu.py
- tests/test_schema.py
- vendor/python_accept_types/LICENSE
- vendor/python_accept_types/accept_types.py
Adds python-accept-types as a 3rd party library for parsing Accept
headers.
> rapu: support multiple accept values and weights

- Makefile
- karapace/master_coordinator.py
poll_heartbeat() needs to be called on regularly following the ensure_active_groups()
> fix schema registry heartbeat

- container/Dockerfile
You only should need to update a few locations and you can now add `--build-arg` to your CI/CD system
> Parameterize the Dockerfile

- Makefile
- container/Dockerfile
- container/docker-compose.yml
- container/start-all.sh
- container/start.sh
Add dockerfile that bundles all karapace needed utilities into one
Update the test dockerfile to also run the rest proxy
Update makefile rules
> Update container related files

- README.rst
- karapace/config.py
- karapace/kafka_rest_apis/__init__.py
- karapace/kafka_rest_apis/consumer_manager.py
Less reliance on class default and more on config defaults will make
the app easier to configure in general
> config: more values for consumers / producers

- dependencies/Makefile
- dependencies/python3-jsonschema/.gitignore
- dependencies/python3-jsonschema/Makefile
- karapace.spec
- karapace/compatibility.py
- karapace/kafka_rest_apis/__init__.py
- karapace/kafka_rest_apis/consumer_manager.py
- karapace/rapu.py
- karapace/schema_reader.py
- karapace/schema_registry_apis.py
- karapace/serialization.py
- requirements-dev.txt
- tests/conftest.py
- tests/test_rest.py
- tests/test_rest_consumer.py
- tests/test_serialization.py
- tests/utils.py
- add typed schemas
- add mock compatibility class
> Jsonschema suport throughout rest / registry requests

- karapace/schema_reader.py
Any unexpected exception in the schema reader message read loop at the
moment will kill the thread and cause the application to become unresponsive
to new writes.
> store: backend loop exception handling

- karapace/schema_reader.py
- tests/test_schema.py
Currently an invalid kafka message encountered in the _schemas topic can
cause the schema reader loop to die. Having a fallback to the validation will
ensure a closer 1 to 1 compatibility
> store: do not perform schema validation

- karapace/compatibility.py
- tests/test_schema.py
Using the equality operator to compare anonymous types with anything else is unreliable, as the `avro.schema.Field`
class does not perform type check inside it's `__eq__` method, resulting
in a compatibility check failing with an unexpected error.
Using our own method for equality check and recursing each field until a
concrete type is encountered brings the logic more in line with the
confluent client
> compatibility: update type comparison logic

- karapace/utils.py
- requirements-dev.txt
Closes #86 and adds packages mentioned in that issue
> Remove circular dependency in utils.py to fix import in rapu.py

- karapace/schema_reader.py
If multiple delete requests for a subject will end up on the kafka
topic, we should properly raise an error
> logic: properly handle missing subject deletion

- tests/conftest.py
- tests/test_schema.py
As discussed here https://github.com/aiven/karapace/issues/97
> compatibility: add test case for full transitive

- karapace/kafka_rest_apis/admin.py
Sometimes the bootstrap node connection will get closed due to lack of
usage, but the admin client needs it for metadata updates, so Canceled
errors will be retried a number of times before bubbling up
> logic: retry failed metadata requests

- karapace/kafka_rest_apis/__init__.py
- karapace/schema_reader.py
- karapace/serialization.py
~I'm going through the code base and adding some type annotations, opened this PR because it *may* have found a bug.~ There was no bug in the code, but in the typing.
I'm still keeping the PR open while the changes are small :)
> Typing for schema registry serializer deserializer

- karapace/statsd.py
> statsd: typing + typo fix

- karapace/schema_reader.py
- karapace/schema_registry_apis.py
- tests/test_schema.py
Previous behavior would return schema string as parsed by Avro, then
reserialized. This might not be desired behavior in all cases and not in
line with SR behavior.
> registry: return schema string as provided

- karapace/utils.py
Before iterating through the connection list to decide which one we want
to keep, make sure we use a copy of it to avoid errors caused by
updating the dict in the same iterating loop
> logic: dispose of blacked out connections safely

- requirements-dev.txt
Added yapf to the dev requirements
> requirements: added yapf

- karapace/schema_backup.py
- requirements-dev.txt
This will make the backup tool more flexible and easier to pipe into
other utilities, should the need arise
> backup: allow stdout location

- karapace/kafka_rest_apis/admin.py
Due to the fact that the patched KafkaClient class will retrieve
metadata in a more reliable fashion, our patched admin client no longer
needs to make metadata requests directed to the bootstrap node, as the
client logic will guarantee an up to date node id list
> rest: admin client metadata request refactor

- karapace/avro_compatibility.py
- tests/test_avro_schema.py
Add alias field / record name matching support to avro compatibility
check
> avro: add alias support

- karapace/schema_backup.py
Because poll works in batches, topics with more than `max_poll_records`
(default of 500) have to be polled multiple times, otherwise only the
first `max_poll_records` are saved by the backup tool.
This assumes there are two timeouts, one for the request and another for
the socket read. A request timeout would occur when the server does not
have additional data to send the client after the timeout, so an empty
response is returned by the server. A socket read timeout happens when
the client is waiting for the server but a response never arrives.
The above is necessary because it allows to use an empty response as an
indicator of "no more data".
> bugfix: fetch all schemas from a large topic

- karapace/kafka_rest_apis/admin.py
Karapace [requires `python>=3.7`](https://github.com/aiven/karapace/blob/4d9524812a9a0ee7be4a26c8f146d0cdd70bdaf0/setup.py#L41), using `six` doesn't make sense anymore
> removed six

- karapace.spec
The spec file was missing the Epoch
> spec: set rpm epoch to 1000

- karapace/schema_registry_apis.py
just a small change to introduce some typing
> rest_api: using Enum with type checking for compatibility levels

- tests/integration/conftest.py
These are just some small cosmetic changes, I started doing this with the idea of randomizing the ports `1234, 5678` so that multiple tests runs could be done in parallel. (It is not guaranteed to be conflict free, as explained in the comments below, but the changes of collision are low enough that it works for me locally).
> Socket port improvements

- .pre-commit-config.yaml
- karapace/kafka_rest_apis/__init__.py
- karapace/kafka_rest_apis/consumer_manager.py
- karapace/karapace.py
- karapace/rapu.py
- karapace/schema_registry_apis.py
- karapace/utils.py
- tests/integration/test_rest_consumer.py
- tests/integration/test_schema.py
This finished the changes started by https://github.com/aiven/karapace/pull/168 https://github.com/aiven/karapace/pull/166
> rapu: HTTPStatus used in the dispatcher.

- tests/integration/test_schema.py
~Depends on https://github.com/aiven/karapace/pull/173~ merged
> added test for avro schema with duplicated name

- tests/integration/test_rest_consumer.py
test_subscription leaves the subscription group in a dirty state after
the test finishes. When executing the tests against containerized
servers this makes the second ran fail.
> tests: fix parallel runs of test_subscription

- tests/integration/test_master_coordinator.py
- tests/integration/test_schema.py
- tests/integration/test_schema_backup.py
- tests/utils.py
This is only a cosmetic change, the only benefit is to have a more descriptive prefix for the subjects.
> tests: cosmetic change, consistently using new_random_name

- karapace/compatibility/__init__.py
- karapace/schema_registry_apis.py
This just adds a bit of documentation in the code about the direction of the compatibility modes.
> Documentation for compatibility modes

- .github/ISSUE_TEMPLATE/01_question.md
- .github/ISSUE_TEMPLATE/02_bug.md
- .github/ISSUE_TEMPLATE/03_feature.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
A few starter templates to encourage and support contributions (even more than before, of course people were always welcome here!).
> Add basic issue/PR templates and a contributing file

- README.rst
After getting a tutorial on setting up my own platform this morning, I've updated the README with instructions that I hope will work for others.
> Add instructions for running locally with docker and without

- README.rst
- container/Dockerfile.registry
- container/Dockerfile.rest
- container/build_image.sh
- container/docker-compose.yml
- container/publish_image.sh
This script can be used to publish an image based on a tag or commit:
> ./container/publish_image.sh 863bf4a7faec3b13eba57a0864e63f5e416cd6e3
> docker: add script to publish image

- README.rst
Main thing: Added info about pre-commit.
Secondary: Organized Local Development chapter, essentially no content change.
> readme.rst Local Development improvements

- CONTRIBUTING.md
I was trying to get these changes in #227, but it was merged in just before I managed to push the changes......
Only minor changes, no essential content change:
Changed some rst formattings to md
Some grammar/typos fixed such as karapace -> Karapace
A few small tweaks
> CONTRIBUTING.md small fixes

- CONTRIBUTING.md
the previous sentence was not really understandable.
> doc: fixed grammar

- README.rst
In the very beginning it now states why Karapace exists.
Wrote more detailed info about the compatibility
> docs, README: clarifying the purpose of Karapace

- tests/integration/test_schema.py
Works now even with external registry.
The issue is that when specifying the registry url etc on the command line `registry_async` is `None` and e.g. `topic` cannot be fetched from that. Added to fetch from the cmd line parameters instead. Not sure if this is the best/correct approach. Actually, `topic` is fixed to `_schemas`. AFAIK we don't have a way to configure that, so it should work?
```
docker-compose -f ./tests/integration/confluent-docker-compose.yml up -d
pytest -vv tests/ --registry-url=http://localhost:8081 --rest-url=http://localhost:8082 --kafka-bootstrap-servers=localhost:9092 -k test_malformed_kafka_message
```
> test_schema.py test_malformed_kafka_message fixes

- .github/ISSUE_TEMPLATE/01_question.md
- .github/ISSUE_TEMPLATE/02_bug.md
- .github/ISSUE_TEMPLATE/03_feature.md
- .github/PULL_REQUEST_TEMPLATE.md
Provide extra comments that would guide contributors on the templates,
but won't be persisted when creating issues or pull requests.
(all contributors please complete this section, including maintainers)
> Provide extra information on github templates

- README.rst
Mention the leader/replica design.
> docs: add note about HA

- karapace/protobuf/schema.py
- karapace/protobuf/utils.py
- tests/unit/test_proto_parser.py
Remove a few places with dead code
> cleanup: removed dead code

- karapace/config.py
~Fixes issues in config.py for pylint==2.4.4~ The warning was silence by another PR, this does some small changes that wouldn't hurt to get in. 
ref: https://github.com/aiven/karapace/pull/303#issuecomment-1024360096
> Config specific exceptions

- karapace/master_coordinator.py
Exclusive lock is not the right abstraction, instead the code should just make the readers wait until the state set by the writer is available, which happens only once.
> karapace: using Event instead of Lock

- karapace/compatibility/jsonschema/checks.py
- karapace/compatibility/jsonschema/utils.py
- karapace/kafka_rest_apis/consumer_manager.py
- karapace/protobuf/io.py
- karapace/protobuf/syntax.py
- karapace/schema_backup.py
- karapace/schema_reader.py
- karapace/serialization.py
- karapace/statsd.py
- setup.py
- tests/integration/conftest.py
- tests/integration/test_rest.py
- tests/integration/test_schema.py
- tests/integration/test_schema_backup.py
- tests/unit/conftest.py
- tests/unit/test_any_tool.py
- tests/unit/test_protobuf_serialization.py
- tests/unit/test_serialization.py
- version.py
This is fixing a few minor issues caught by pylint, the goal is to have them fixed and upgrade pre-commit to version 2.12.2
> pylint fixes

- README.rst
Karapace now supports Protobuf schemas
Fixes #67
> Update Protobuf status

- karapace/serialization.py
- tests/unit/test_serialization.py
Fix for https://github.com/aiven/karapace/issues/319
When encoding Avro messages to JSON, per the spec, enums have to be tagged unions [ref](https://avro.apache.org/docs/current/spec.html#json_encoding).
So for this schema:
```json
{
"namespace": "io.aiven.data",
"name": "Test",
"type": "record",
"fields": [
{
"name": "attr",
"type": [
"null",
"string"
]
}
]
}
```
this is the correct encoding:
```json
{"attr":{"string":"sample data"}}
```
The library does not have a JSON encoder or decoder [AVRO-91](https://issues.apache.org/jira/browse/AVRO-91).
To support JSON messages, Karapace is using a JSON library, without handling the exception above. This works for everything but unions. The JSON representation needs to be transformed to the Python representation by removing the tag.
From: …
> rest proxy: handle union fields

- README.rst
> Fix typo in readme.rst

- README.rst
Karapace REST adress is wrongly configured in curl snippets
> Fix Karapace REST address in readme

- .pre-commit-config.yaml
- karapace/protobuf/compare_type_storage.py
- requirements-dev.txt
- tests/utils.py
Updates black to circumvent an issue with click, ref: https://github.com/psf/black/issues/2969
Build logs of another PR with the same error: https://github.com/aiven/karapace/runs/5735453639?check_suite_focus=true
I would also have updated pylint, but that needs quite a few a changes
> Update precommit tools

- karapace/config.py
- karapace/kafka_rest_apis/__init__.py
- karapace/karapace.py
- karapace/karapace_all.py
- karapace/rapu.py
- karapace/schema_registry_apis.py
This unifies how the sentry configuration is set
> Simplified sentry config

- karapace/schema_registry_apis.py
This endpoint is for all formats
> schema_registry: removed misleading comment

- tests/integration/conftest.py
- tests/integration/test_schema_reader.py
- tests/unit/conftest.py
These issues sneaked in when pylint was upgrade (and two other PRs touched the same module).
> pylint: fix linting issues

- .pre-commit-config.yaml
- karapace/anonymize_schemas/anonymize_avro.py
- tests/integration/test_schema_backup_avro_export.py
- tests/unit/anonymize_schemas/test_anonymize_avro.py
Fix linting issues. They happened because PRs where merged concurrently (tools were upgraded, code was refactored, and functionality PRs were merged)
> Fix linting issues

- .github/workflows/tests.yml
- karapace/schema_backup.py
- requirements-dev.txt
- tests/integration/conftest.py
- tests/integration/test_master_coordinator.py
- tests/integration/test_schema.py
- tests/integration/test_schema_backup.py
- tests/integration/test_schema_backup_avro_export.py
- tests/integration/utils/cluster.py
- tests/integration/utils/network.py
- tests/utils.py
This probably doesn't fix all the issues, but it should handle the last spike in flakiness. The PR could definitely have better commits, I just ran out of time :P
> Fix flakiness

- karapace/client.py
- karapace/schema_registry_apis.py
- karapace/typing.py
- tests/integration/test_schema.py
This is a follow up to #384, that PR was big already.
Same thing. It reduces logging level, number of logging calls, fixes some bugs that I found while reviewing the logs, and no longer logs the contents of the schemas.
> Reduced logging

- karapace/schema_reader.py
for usage patterns where the same instance is registered regularly, the
increase in memory pressure is measurable and can cause Karapace to be
OOM'ed. This commits improves the situation by reusing existing schemas
based on their content, instead of having multiple copies of the same
schema in memory.
> performance: added schema reused based on content

- karapace/compatibility/__init__.py
- karapace/errors.py
- karapace/schema_models.py
- karapace/schema_reader.py
- karapace/schema_registry.py
- karapace/schema_registry_apis.py
- tests/integration/test_schema.py
- tests/unit/compatibility/test_compatibility.py
Set of commits that improve Karapace API compatibility with Confluent Schema Registry.
> Improve Karapace API compatibility with Confluent Schema Registry API

- karapace/schema_backup.py
- tests/integration/test_schema_backup.py
Format schema record keys in canonical format when doing a backup.
Format schema record keys in canonical format when restoring a backup.
The key formatting is restricted to `schemas` topic or when explicitly from configuration. The backup tool has dual use, it is not onyl used to backup Karapace but can be used to backup any Kafka topic.
> feature: do key correction on backup get and restore

- karapace/schema_reader.py
* report count of processed records per keymode, counter
* report number of of processed records per keymode, gauge
* report number of of schemas and subjects, gauge
* report number of live and soft deleted schema versions, gauge
> metrics: report Karapace processing metrics

- karapace/key_format.py
- karapace/schema_registry.py
Fix key JSON compact form
References: #458 triggered a case where JSON key was written in non-compact form.
> Fix key JSON compact form

- karapace/schema_registry_apis.py
- tests/integration/test_schema.py
Fix registering after odd hard delete
If initial state contains only hard delete skipping soft delete message, hash cache for schema ids is not cleaned correctly.  Add a test with manually created odd initial state, and verify that registering a schema into such subject works after.
> Fix registering after odd hard delete

- karapace/schema_reader.py
- karapace/schema_registry_apis.py
- tests/integration/test_schema.py
Fix Internal Server Error deleting unknown subject
Catch exception if subject know found correctly, and add integration tests for this behaviour.
> Fix Internal Server Error deleting unknown subject

- karapace/master_coordinator.py
Add Karapace version to primary node coordinator metadata.
> Add Karapace version to primary node coordinator metadata

- karapace/schema_registry.py
For tracing the source registry and its version of the schema record.
> Send source registry in Kafka record headers

- version.py
Sometimes the Git metadata is not available during build. In this case, we can rely on externally specified version using the `KARAPACE_VERSION` environment variable.
> Allow specifying version directly during build

- karapace/schema_reader.py
Handle `InvalidReplicationFactorError` during startup
When Kafka brokers are still starting up, handle `InvalidReplicationFactorError` without logging it as an exception as it retrying will solve the  situation.
> Handle InvalidReplicationFactorError during startup

- website/source/_static/js/snowplow.js
This is the new version that we are running on the collector side.
> website: update snowplow postPath parameter to new value

- karapace/master_coordinator.py
The primary coordinator main loop shall not use zero sleep when heartbeat has been missed. Use half of the heartbeat interval in that case.
Issue symptom is visible with debug log level when `We're master ...` is logged multiple times.
> fix: use sane sleep on primary coordinator main loop

- .pre-commit-config.yaml
- karapace/auth.py
- karapace/kafka_rest_apis/admin.py
- karapace/master_coordinator.py
- karapace/protobuf/proto_parser.py
- karapace/protobuf/protobuf_to_dict.py
- karapace/rapu.py
- karapace/schema_backup.py
- karapace/schema_registry.py
- karapace/serialization.py
- karapace/statsd.py
- karapace/utils.py
- setup.py
- tests/integration/test_rest.py
- tests/integration/test_rest_consumer.py
- tests/integration/test_schema.py
- tests/integration/test_schema_backup.py
- tests/integration/utils/cluster.py
- tests/integration/utils/kafka_server.py
- tests/integration/utils/network.py
- version.py
Adds and applies the [pyupgrade](https://github.com/asottile/pyupgrade) pre-commit hook.
Note that configuration and application is split into two separate commits to help in reviewing, we can squash merge those.
Automates keeping up with new Python syntax, helping in maintaining project help and reduces items to address in review.
> chore: Add pyupgrade pre-commit hook

- karapace/auth.py
- karapace/config.py
- karapace/kafka_rest_apis/__init__.py
- karapace/kafka_rest_apis/consumer_manager.py
- karapace/key_format.py
- karapace/master_coordinator.py
- karapace/rapu.py
- karapace/schema_backup.py
- karapace/schema_models.py
- karapace/schema_reader.py
- karapace/schema_registry_apis.py
- karapace/serialization.py
- karapace/utils.py
- requirements.txt
- setup.py
- tests/integration/test_schema.py
- tests/integration/test_schema_backup_avro_export.py
- tests/unit/test_avro_compatibility.py
UltraJson gives slight performance improvement.
Decided to support the vanilla `json` and `ultrajson` for now.
> feat: use UltraJSON if available

- karapace/kafka_rest_apis/__init__.py
- karapace/rapu.py
- karapace/schema_registry_apis.py
- tests/integration/test_schema.py
Fix handling of miscellaneous errors and input validation
Separate commits fix different cases of input validation or call handling situations.  Each fix per case was quite small, therefore include all four in one pull request.
> Miscellaneous error handling fixes

- karapace/master_coordinator.py
Reformat code to fix semantical conflict with linting after merging #570
> Fix semantical conflict with linting

- tests/integration/utils/network.py
Don't try to be smart about port choices on Macos, use random choice instead.
Running the test suite on Macos currently raises `psutil.AccessDenied` stemming from `is_time_wait` used by `PortRangeInclusive`.
> fix: randomly choose test ports on non-linux systems

- README.rst
Fix test status badge's branch and target link
> Fix test status badge's branch and target link

- .pre-commit-config.yaml
- requirements/requirements-dev.txt
- Bump requirements.
- Bump pre-commit hooks.
> chore: Bump dependencies

- karapace/dependency.py
- karapace/errors.py
- karapace/in_memory_database.py
- karapace/schema_models.py
- karapace/schema_reader.py
- karapace/schema_references.py
- karapace/schema_registry.py
- karapace/statsd.py
- karapace/typing.py
- mypy.ini
- tests/integration/backup/test_legacy_backup.py
- Add type hints to `karapace.schema_reader`. While doing this, discovered a few inconsistencies needing addressing to pass static type checking.
- Replace type aliases with `NewType`s.
Increase type coverage.
> chore: Add type hints karapace.schema_reader

- karapace/config.py
- karapace/sentry/__init__.py
- karapace/sentry/sentry_client.py
- karapace/sentry/sentry_client_api.py
- karapace/statsd.py
- mypy.ini
Add type-hints to statsd modules.
Increase type coverage.
> chore: Add type-hints to statsd modules

- karapace/protobuf/io.py
- karapace/protobuf/protobuf_to_dict.py
- mypy.ini
> chore: Add type hints to karapace.protobuf.io

- karapace/config.py
- karapace/kafka_rest_apis/admin.py
- karapace/protobuf/enum_constant_element.py
- karapace/protobuf/exception.py
- karapace/protobuf/extensions_element.py
- karapace/protobuf/location.py
- karapace/protobuf/proto_file_element.py
- karapace/protobuf/rpc_element.py
- karapace/protobuf/schema.py
- mypy.ini
- tests/unit/protobuf/test_compare_elements.py
- tests/unit/protobuf/test_enum_element.py
- tests/unit/protobuf/test_extend_element.py
- tests/unit/protobuf/test_extensions_element.py
- tests/unit/protobuf/test_field_element.py
- tests/unit/protobuf/test_message_element.py
- tests/unit/protobuf/test_proto_file_element.py
- tests/unit/protobuf/test_proto_parser.py
- tests/unit/protobuf/test_protobuf_compatibility.py
- tests/unit/protobuf/test_protobuf_schema.py
- tests/unit/protobuf/test_service_element.py
Add type hints and some minor refactorings for better static checking with mypy.
This contains only easy wins to enable more mypy check coverage.  See individual commits for more details if needed.
> Improve typing and enable mypy checks for many modules

- karapace/schema_reader.py
Rename internal variable to avoid overriding `Thread._stop()`
Don't override `Thread._stop()` with internal `Event()` instance.  This caused internal exception after process forking for producing ProtoBuf messages from REST Proxy.
> Rename internal variable to avoid overriding Thread._stop()

- karapace/schema_registry_apis.py
- tests/integration/test_schema_registry_auth.py
Fix authentication check with referencedby route
> Fix authentication check with referencedby route

- .github/ISSUE_TEMPLATE/03_feature.md
Show a nice clickable checkbox when creating a new issue. :)
> Fix issue template to actually show checbox

- README.rst
Name strategy options fix in README.
> Fix name strategy options in README

- karapace/kafka_rest_apis/__init__.py
> Remove unused assignment

- karapace/schema_reader.py
Handle `UnknownTopicOrPartitionError` in `._is_ready()` check after seeing this in production.
All exceptions should be handled.
> Handle UnknownTopicOrPartitionError in schema reader

- karapace/schema_reader.py
Schema reader ignores messages that cannot be parsed currently by catch-all exception handler.  Those are not errors as Schema Registry works by skipping those messages that cannot be utilized, so convert logging to warning level.  Also handle KeyError in case some fields are missing from messages.
> Convert non-parseable schema messages to warning

- .github/workflows/lint.yml
- .github/workflows/schema.yml
- .github/workflows/tests.yml
Update GitHub actions to the latest versions.
> Update GitHub actions versions

- requirements/requirements-dev.txt
- requirements/requirements-typing.txt
- requirements/requirements.in
- requirements/requirements.txt
> chore: update requirements

- karapace/kafka_utils.py
- tests/integration/backup/test_session_timeout.py
- tests/integration/conftest.py
- tests/integration/utils/kafka_server.py
> feat: enable the customization of the kafka properties

- .github/workflows/tests.yml
See: https://github.com/py-cov-action/python-coverage-comment-action/issues/470
> chore: include hidden files when uploading coverage

- tests/integration/test_schema_coordinator.py
> test: add retries to schema coordinator workflow test

- .github/workflows/container.yml
> fix: change the label for the workflow

- tests/unit/test_main.py
Add tests to src/karapace/__main__.py, as currently there are no tests
> Adding test for main

- requirements/requirements-dev.txt
- requirements/requirements-typing.txt
- requirements/requirements.txt
Had to upgrade httpcore to 1.0.9 to upgrade h11 to 0.16.0
> Upgrade h11 & httpcore

- requirements/requirements-dev.txt
- requirements/requirements-typing.txt
- requirements/requirements.txt
> Upgrade aiohttp, yarl

- README.rst
> Updating features

- README.rst
- container/compose.yml
- container/keycloak/realm-export.json
- src/karapace/api/middlewares/__init__.py
- src/karapace/api/oidc/middleware.py
> Docker configs authorization

- tests/e2e/conftest.py
- tests/e2e/schema_registry/test_jsonschema.py
> e2e tests oidc

- tests/integration/test_schema_protobuf.py
We try to reproduce a situation where the API allowed the deletion of a schema that was still referenced, but as the tests show, this should not be possible.
> [v4] tests: deletion of multi-referenced schema
