.gitignore, Makefile, karapace/version.py
Additionally the file is now always generated before running tests.
=> version: ignore the autogenerated file in version control

karapace/karapace.py, karapace/rapu.py, tests/test_schema.py, tests/utils.py
Previously only application/vnd.schemaregistry.v1+json was returned
regardless of which Accept header was sent. Now the API responds with
the correct value.
=> karapace: fix response content types

karapace/karapace.py, tests/test_schema.py
The endpoint included an extra "deleted" field and was missing a "subject" field.
=> karapace: fix return fields for schema check endpoint

dependencies/python3-kafka/Makefile
To make use of zstd compression , until the parent repo is up to date
=> kafka: temporarily update the kafka client repo ref to the aiven fork

karapace/schema_reader.py, tests/test_schema.py
Previously this was also assigned when using existing schemas which ended
up creating duplicate id values.
=> schema_reader: copy global schema id value only on new schemas

karapace/rapu.py, tests/test_schema.py
Some older clients use application/octet-stream as the Content-Type
value. The content is interpreted to be JSON.
=> rapu: support application/octet-stream for schema requests

karapace/rapu.py, karapace/utils.py, tests/test_schema.py
Previous implementation failed when charsets were defined and
additionally it forced to use UTF-8 only.
=> rapu: parse content-type charsets correctly

karapace/compatibility.py, tests/test_schema.py
Compatibility checks are extended to support Union, Array, Map and Fixed
types both directly and nested. Primitive and Enum schemas can now also
be used directly and not only in a nested record structure. The simple
presentation for types in maps and arrays is also made to look at
compatibility promotions correctly. In addition, the test suite is
extended with more schema checks to increase coverage.
=> compatibility: extend supported types

karapace/rapu.py, tests/test_schema.py, tests/test_web_app.py
Header search will try to ignore case. Missing Content-Type
headers will default in application/json.
=> Handle missing and miscased content headers

README.rst
The project has moved to using Github actions so the Travis build status
badge is no longer needed.
=> README: remove travis build status

karapace/schema_reader.py
Importing just the root avro package and then making use of that to
access the Schema type will break the backup tool in executable mode.
This aims to fix that issue by directly importing all needed types /
functions from the avro package
=> imports: use explicit avro imports

karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/admin.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/karapace.py
The default 9 minute idle connection closing is too lenient for
scenarios like maintaining a valid connection pool through a cluster
update.
Injecting a configurable lower value "should" lower the
possibility of clients with a connection pool where the majority of
connections are broken
=> client: more aggresive idle conn recycling

karapace/compatibility.py, tests/test_schema.py
check_same_type now accounts for multiple forms of union types, since we
can end up calling this method from multiple places
=> compatibility: same type checks for union

karapace/schema_reader.py, karapace/schema_registry_apis.py, tests/conftest.py, tests/test_master_coordinator.py
Allow storing message offsets for config type messages no matter the
node state, since all node types will accept config type requests
and send relevant messages on the kafka topic, thus in certain scenarios
(single node not ready, but server is up) causing writes to
succeed but offsets to be lost, and thus requests to hang indefinitely
=> compatibility: config msg offsets while not ready

tests/conftest.py, tests/test_schema.py, tests/test_schema_backup.py, tests/test_serialization.py
Use a separate unittest instead of a check function to better split the
tests. Remove unused fixtures
WARNING: Test run time is increased due to the registry fixture being
recreated for almost each test in the suite
Wait for kafka cluster using an admin client instead of a tcp check in
hope of catching broken kafka / zk fixtures earlier
=> tests: refactor schema tests

README.rst, karapace/config.py
Read environment variables for KARAPACE_*  pattern and allow that parsed
value to take precendence over file config. This is done mostly to allow
easy configuration of a docker container, or just for convenience when
dealing with non sensitive config values
=> config: allow env vars to take precedence

Makefile, karapace.config.json, karapace/config.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/master_coordinator.py, karapace/schema_reader.py
Having the kafka cluster configured with value for
group.min.session.timeout.ms exceeding the default session_timeout_ms
value (10s) will cause JoinGroup requests to fail. Making
session_timeout_ms, as well request_timeout_ms (which should always be
larger) configurable will allow one to work around that limitation
The stop-kafka make target did not previously cleanup the zk / kafka log
folders, which would cause subsequent cluster restarts to fail due to
preexisting data
=> config: add session_timeout_ms config param

karapace/kafka_rest_apis/__init__.py, karapace/karapace.py, karapace/master_coordinator.py, karapace/schema_backup.py, karapace/schema_reader.py, karapace/utils.py, requirements-dev.txt
Patch the karapace kafka client to only make metadata calls to the
bootstrap node. This will fix a bug where metadata calls would end up
continuously being made to no longer valid connections, resulting in a
stale metadata, log spam and probably decreased performance
=> logic: metadata requests to bootstrap nodes

karapace/master_coordinator.py
Pass the config value all the way down to the SchemaCoordinator instead
of hardcoding the value to True
=> logic: configurable master eligibility

karapace/schema_reader.py, karapace/utils.py
Metadata updates will ensure we have access to an up to date broker list
for sending requests, but the client connection list can still hold
stale connections.
- Make sure we blackout requests failing with DNS errors
- If we encounter any such connections, close them and then force a
metadata update
- Actually pass the metadata_max_age parameter to the SR consumer, as
previously only the producer would make use of it
=> logic: block ns failed connections

README.rst, karapace/config.py, karapace/master_coordinator.py, tests/test_master_coordinator.py
Having the highest cluster node instead of the lowest one be the master
will in theory ensure that newer cluster members are immediately
eligible, thus preventing slaves pointing to dead / killed masters
=> logic: update master election logic

karapace/avro_compatibility.py, karapace/schema_reader.py, tests/conftest.py, tests/test_avro_schema.py
This is the initial port of the tests, commented out tests are:
- Relying in the schema8, which is not parseable by the avro library (it looks like it is a sequence of items separated by a single `,`)
- Doing transitivity tests. These need to be reviewed in more detail to understand what is the proper behaviour. It is not clear which of the "legs" in the chain is breaking the schema compatibility
- There seems to be a few bugs with backwards and forwards compatibility that were commented out
=> tests: ported avro compatibility tests

tests/conftest.py, tests/test_master_coordinator.py, tests/utils.py
As the title says, this just adds type information to the conftest.
While adding the typing annotations I noticed some fixtures are conditional in respect to the env variables `REST_URI` and `REGISTRY_URI`. From the commit history it looks like these are just artifacts from how the tests used to be executed. I guess they should eventually be removed.
=> Added typing info to conftest.py

karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/__main__.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/karapace.py, karapace/karapace_all.py, karapace/schema_backup.py, karapace/schema_registry_apis.py, karapace/serialization.py, tests/conftest.py, tests/test_serialization.py
This change the code so that the configuration file is read only once at the `main`. I'm doing this for a few reasons:
- I want to eventually add validation for the configuration and make it a dataclass. This will make it possible to have type checking and auto completion for the config, have faster errors on improper configuration, and make it easier to document all the available options. (some of that, but not all, is done by the [`set_config_defaults`](https://github.com/aiven/karapace/blob/master/karapace/config.py#L68-L81))
- This should also make testing easier, since files won't be necessary any longer. ATM I couldn't remove the file path because the fixtures are piggybacking into the class state and getting the path.
- This also makes sure the config is consistent, in the unlikely …
=> karapace: read configuration only once

karapace/serialization.py, requirements-dev.txt
Update aiohttp-socks ~and fix code to work with `aiohttp>=3.6.0`~ The code does work with `aiohttp>=3.6`, the removal of the `loop` argument is only for `aiohttp>=4` which is still on alpha.
=> updated aiohttp-socks

karapace/kafka_rest_apis/__init__.py, karapace/karapace.py, karapace/schema_backup.py, karapace/schema_reader.py, requirements-dev.txt
`git+git://github.com/aiven/kafka-python.git@346c01e4eec6bdcccc99ca613b79020f3be35eb7` ~is the current commit for https://github.com/aiven/kafka-python/tree/aiven_patches , which is rebased on top of dpkp's master.~ `master` was updated instead, it is the same commit but now master points to it.
During the review fo https://github.com/dpkp/kafka-python/pull/2144 the configuration key changed name.
=> Update kafka-python and fix api change.

karapace/kafka_rest_apis/admin.py, requirements-dev.txt
Upstream issue: https://github.com/dpkp/kafka-python/issues/2193
Note: This PR should not be merged before dependency `kafka-python` is updated, or we merge the patch to our repo https://github.com/aiven/kafka-python/pull/20
Calling `_send_request_to_node` with the result of `least_loaded_node`
results in an infinite loop if the metadata is out-dated and
`least_loaded_node` return the `node_id` of a broker that was removed
from the cluster. The method `_send_request_to_least_loaded_node`
handles this race and fixes the infinite loop.
=> bugfix: fix infinite loop

requirements-dev.txt, setup.py
For now this just defines the abstract dependencies to start the fix, but it may need additional work for the concrete dependencies. The problem is that we use these two dependencies with patches for development:
```
git+https://github.com/aiven/avro.git@skip-namespace-validation#subdirectory=lang/py3/
git+git://github.com/aiven/kafka-python.git@b9f2f78377d56392f61cba8856dc6c02ae841b79 
```
And if our repo relies on a patched API installing the vanilla dependencies may not be sufficient.
=> setup.py: added package dependencies

Makefile, container/Dockerfile, karapace.spec
The previous mirror is returning `404` causing the build to fail:
```
wget "http://www.nic.funet.fi/pub/mirrors/apache.org/kafka/2.4.1/kafka_2.12-2.4.1.tgz"
--2021-02-01 08:18:01--  http://www.nic.funet.fi/pub/mirrors/apache.org/kafka/2.4.1/kafka_2.12-2.4.1.tgz
Resolving www.nic.funet.fi (www.nic.funet.fi)... 193.166.3.3, 2001:708:10:8::3
Connecting to www.nic.funet.fi (www.nic.funet.fi)|193.166.3.3|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-02-01 08:18:02 ERROR 404: Not Found.
make: *** [kafka_2.12-2.4.1.tgz] Error 8
Makefile:41: recipe for target 'kafka_2.12-2.4.1.tgz' failed
Error: Process completed with exit code 2.
```
=> Update kafka mirror

version.py
```
The current Makefile doesn't have a `short_ver` variable. It does have a
`SHORT_VER`, however, that is a shell command which is only expanded by
`make`.
```
=> version: don't read Makefile short_ver

tests/unit/test_web_app.py
As the PR title says. The goal here is more to have examples of the matching strings to make it easier to understand what to expect from the regex groups
=> tests: added test for accept header regex

karapace/schema_registry_apis.py
My idea here is to remove the magic constants that we have through out the code and give them a name, the end goal is to use these variables in the tests so that when a test fails the enum name gives a hint on what went wrong.
=> Schema registry APIs using enum for error codes

pytest.ini, requirements-dev.txt, tests/integration/test_master_coordinator.py
https://github.com/aiven/karapace/pull/161/commits/2070989380ff9cd99d47c719c65cbd0721f5d610 didn't fix the flakiness, https://github.com/aiven/karapace/pull/165 failed with the same test. I did a more thorough review and I think I found the cause of flakiness: 
The condition `if not (a or b)` is true only if both `a` and `b` are
false.
Truth table:
a | b | a or b | not (a or b)
f | f |   f    |       t
t | f |   t    |       f *
f | t |   t    |       f *
t | t |   t    |       f
The cases with an asterisk above should cause flakiness in the test,
because setting the master flag and the url is not atomic. So the
condition can be partially satisfied.
=> Fix flakiness of test_master_selection

karapace/avro_compatibility.py, karapace/compatibility.py, karapace/schema_registry_apis.py
This does a few things
- Simplifies the code of `Compatibility`, it can be just a single function call
- Adds typing info and some docs to `SchemaCompatibilityResult`, I want to reuse this class with JSON schema
The goal was not to change any behavior just to document and simplify. I'm saying this because `check_compatibility` will need some refactoring. ATM this function is used only for the exceptions it raises, IOW, the return value is ignored by every caller. It makes a bit hard to reason if the callers are working as intended because `False` is returned is for unsupported formats (e.g. json schema and protobuf). I believe the code is behaving correctly because there are checks earlier in the code, but still, local reasoning is not great here.
=> Added typing to the SchemaCompatibilityResult class

tests/integration/conftest.py, tests/utils.py
- pickle encodes the object's absolute module location while encoding, and
use it while decoding.
- pytest will change the top-level module depending on the arguments it
is provided, breaking pickle decoding.
This changes to use json, since that does not depends on the above.
=> tests: replaced pickle with json

tests/integration/test_client.py
The subject `foo` is left is a dirty state, when running with an external service only the first run will be successful. This fixes the issue by using a new subject for every run.
=> tests: allow repeated execution of test_remote_client

tests/integration/conftest.py, tests/integration/test_master_coordinator.py, tests/integration/test_rest.py, tests/integration/test_rest_consumer.py, tests/integration/test_schema.py, tests/integration/test_schema_backup.py, tests/utils.py
~Depends on  #180~
The test for master selection couldn't be run in parallel because the port numbers, group ids, and clients ids conflicted. This changes the test to use random values fixing the flakiness.
I tested this with:
```
(cd containers; sudo docker-compose --project-name karapace up -d)
while [[ $? == 0 ]]; do pytest tests -vvv -x --registry-url http://localhost:8081 --rest-url http://localhost:8082/ --kafka-bootstrap-servers localhost:9092 -k test_master_selection; done
```
=> Fix test master selection and tests with timings issues for topics

pytest.ini
30 seconds is not sufficient is some cases to run zookeeper and kafka on
github workflows, this is causing flakiness:
Here is an example of a flakiness:
2021-03-24T09:18:02.7723927Z tests/integration/test_client.py::test_remote_client[pyloop]
2021-03-24T09:18:02.7743108Z filelock MainThread INFO Lock 140042435949008 acquired
2021-03-24T09:18:20.8720742Z filelock MainThread INFO Lock 140401743256016 released
...
2021-03-24T09:18:32.7708050Z Timeout
It took 18secs to start the servers, and the additional 12secs was not
sufficient for the two karapace servers started by `registry_async_pair`
to finish starting.
=> tests: increase test timeout

karapace/config.py, karapace/kafka_rest_apis/__main__.py, karapace/karapace.py, karapace/karapace_all.py, karapace/schema_registry_apis.py, tests/integration/conftest.py
Configuring the logging in the base class constructor interferes with
the testing runner configuration, it effectively overwrites pytest's
configuration making the flag `--log-cli-level` unusable.
=> Early log level configuration

karapace/config.py, karapace/kafka_rest_apis/__main__.py, karapace/karapace.py, karapace/karapace_all.py, karapace/schema_backup.py, karapace/schema_registry_apis.py, tests/integration/conftest.py, tests/integration/test_schema_backup.py
depend on #188
The test was relying on `registry_async`, which will be set to `None` after #189 is merged. This change allows to run the test again with the `--registry-url` flag.
=> Fix tests backup

tests/integration/conftest.py, tests/utils.py
Otherwise the services will join the existing group and the tests may
fail if the services started by the fixtures can not communicate with
the external services.
=> tests: dont run rest/registry if external services are used

karapace/schema_backup.py
It is possible to generate empty backup files, this should not be
treated as an error.
=> schema_backup: do not treat empty files as an error

karapace/compatibility/jsonschema/utils.py, tests/integration/schema_registry/test_jsonschema.py, tests/unit/test_json_schema.py
Fix `propertyNames` support: An object with `propertyNames` setting constraints on property names is still open ie. there are no limitations on property values for those.
Add separate test for object properties without `propertyNames` and fix test to match existing integration test.
=> JSON Schema propertyNames compatibility

karapace/schema_registry_apis.py, tests/integration/test_schema.py, tests/utils.py
Added support for a missing API call
https://docs.confluent.io/platform/current/schema-registry/develop/api.html#get--schemas-ids-int-%20id-versions
Note the test `test_schema_versions_multiple_subjects_with_same_schema` doesn't work (yet) against Schema Registry. There are other tests too that don't work against it. The idea is to fix them all in a separate PR.
=> Schema versions

README.rst, tests/integration/confluent-docker-compose.yml
Instructions in README.rst
Docker Compose file to start the Confluence stack
(all contributors please complete this section, including maintainers)
=> Added information how to run integration tests against Confluence stack

README.rst
The main `README.rst` file contained the list of Configuration keys listed one after the other. The current version includes them in a table format improving readability
=> Ft fix readme Configuration keys as table

tests/integration/test_schema.py, tests/utils.py
Splitting `test_schema` (https://github.com/aiven/karapace/blob/master/tests/integration/test_schema.py#L1099) function in the integration tests to multiple test methods. Currently the function does so much that it's hard to understand what it actually does. The reason for splitting is to make the test more readable and maintainable. #222 is based on this refactored test code.
=> Split test schema

karapace/schema_registry_apis.py, tests/integration/test_schema.py
The error message in POST to /subject/<subject> when schema is not specified in the request changed.
Fixes test_schema_subject_post_invalid to run in Karapace and against Schema Registry.
=> schema_registry: breaking change in an error message

karapace/schema_registry_apis.py, tests/integration/test_schema.py
Fixed the error message in subjects/{}/versions/{} to match Schema Registry
Now test_schema_subject_invalid_id works against SR
=> schema_registry: breaking change in subjects/{}/versions/{}

karapace/schema_registry_apis.py, tests/integration/test_schema.py
In the case the endpoint is submitted without body, changed the HTTP status code, error_code and message match the ones in Schema Registry. Made the necessary changes so that Karapace also returns correct values.
test_schema.py: test_schema_missing_body fixed accordingly.
=> schema_registry: breaking change in POST subjects/{subject}/versions

karapace/schema_registry_apis.py, tests/integration/test_schema.py
/schemas/ids/<schema_id:path>/versions now returns empty list in case nothing is found.
This is the behaviour of SR. Karapace used to fail in this case before this change.
The tests test_schema_lifecycle and test_schema_versions_deleting now works against Schema Registry (in addition to Karapace)
=>  schema_registry: breaking change in /schemas/ids/<>/versions

karapace/rapu.py, tests/integration/test_schema.py
Now HTTP error messages match with the ones coming from Schema Registry.
Adjusted test_http_headers in test_schema.py to correctly check the messages.
Since the Kafka REST and Schema Registry REST share `rapu.py`, I assume this will also change the error messages in Kafka REST? Is that OK? Do we test those errors?
=> schema_registry: breaking changes in some HTTP error messages

CONTRIBUTING.md, README.rst
- Moved development docs from README to CONTRIBUTING
- Made the instructions more concise
- Removed some outdated documentation, e.g. python 3.6 is no longer supported
- Made the README.rst a bit more concise.
- Also added a mention to the supported formats and a link to the issue for protobuf support which is currently in dev
=> readme: clarified and separated readme

karapace/master_coordinator.py, karapace/schema_reader.py, karapace/schema_registry_apis.py, tests/integration/test_master_coordinator.py
Karapace configuration allows configuring node to not be eligible for master.  Handle gracefully ie. read-only mode if all nodes are configured non-eligible for master.
=> Handle gracefully if no node is master eligible

karapace/schema_registry_apis.py
When started from `KarapaceAll`, the `__init__` of KarapaceSchemaRegistry is not called.
schema_lock is initialized in `__init__`. Thus it's not called when using `KarapaceAll`.
Fix is to move `schema_lock` init to `_init()` which gets called also when using `KarapaceAll`.
=> KarapaceAll: startup fix

CONTRIBUTING.md
Not very easy to spot why the tests are failing if following the instruction with the typo.... The tests just timeout.
=> docs: locahost -> localhost

karapace/statsd.py
When running the tests we get these errors:
> 2021-06-04T08:28:15.1782569Z ERROR    StatsClient:statsd.py:126 Unexpected exception in statsd send: AttributeError: 'NoneType' object has no attribute 'copy'
It seems it was caused by this line:
https://github.com/aiven/karapace/blob/fa7211f3fe3f20f4ccc8d306303b3dd97655ea03/karapace/statsd.py#L107
The bug was caught by `mypy`, unfortunately I think it is not yet enforced in the CI.
=> bugfix: _tags should default to a dict

version.py
Usage of `imp` is deprecated, when running `pytest tests/unit` the following warnings are printed:
```
bringing up nodes...                  
................................................                                                                                                                                                                                       [100%]
============================================================================================================== warnings summary ==============================================================================================================
version.py:7
version.py:7
version.py:7
version.py:7
/home/hacka/work/karapace/version.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the …
```
=> fix: imp module is deprecated

tests/integration/conftest.py
Unfortunately this is not written in the aiohttp documentation, but it is in the code:
https://github.com/aio-libs/aiohttp/blob/1520b8fbb15b5d8860cef04de961d9669f73d219/aiohttp/pytest_plugin.py#L82-L89
=> bugfix: async fixtures must depend on loop

README.rst
Add command into readme how to register a version of a schema using JSON Schema. Fixes #253
=> Add example command to register JSON Schema

tests/integration/test_schema.py
Using a unique schema name to support parallel execution.
Small improvement in the assert messages.
The test doesn't work against Schema Registry. The issue is that SR doesn't reuse the same schema id after hard delete. Karapace reuses.
We still can merge this PR and handle the incompatibility in another PR.
=> test_schema.py: test_schema_hard_delete_and_recreate

karapace/schema_registry_apis.py, tests/integration/test_schema.py
Making changes to Karapace Schema Registry for Schema Registy-compatibility.
```shell
docker-compose -f ./tests/integration/confluent-docker-compose.yml up -d
pytest -vv tests/ --registry-url=http://localhost:8081 --rest-url=http://localhost:8082 --kafka-bootstrap-servers=localhost:9092 -k test_config
```
=> sr-compat: Error messages in config_set and in config_subject_get

README.rst
Refs: #266
Provides instructions for both Docker and Python installation
It matters because a good README should provide means to install and uninstall the product / library.
=> Add uninstall instructions #266

container/docker-compose.yml, container/start.sh, karapace/config.py
The previous `start.sh` had two issues. 1. It gave the impression configurations had to be manually saved to the configuration file 2. it had some bad defaults for ssh. This caused trouble to some users: https://github.com/aiven/karapace/pull/219 https://github.com/aiven/karapace/pull/263 . This PR modifies the `start.sh` with a comment explaining about the `KARAPACE_` env variables, and changes the existing script to use that too.
=> Container accepting all config options

.github/workflows/lint.yml, .github/workflows/tests.yml
References: #271
Lint and tests will now run when:
- A PR is created, updated, reopened...
- A push event happens on the master branch
=> Config GitHub actions to avoid double triggering #271

CONTRIBUTING.md, README.rst
Words like easy, painless, straightforward, trivial, simple and just
when referring to simplicity should be avoided from any docs.
Just might be OK to use when it referst to the temporal adverb, like
"the thing we did just before".
=> Clean up obsolete sections and remove "simply" wording

CODE_OF_CONDUCT.md, README.rst
Add the code of conduct (https://www.contributor-covenant.org/ v2.1) with Aiven's contact details to the project. Added the badge to the readme (and updated the copyright year while I was there)
I suggest we review and discuss here, but leave open for any community comments or feedback for a couple of weeks before merging.
=> Add a code of conduct for the project

karapace/schema_reader.py, karapace/schema_registry_apis.py, tests/integration/test_schema.py
This provides a bit more of context of the error to the user
=> schemas: better error messages for invalid schemas

karapace/avro_compatibility.py, tests/integration/test_schema.py, tests/unit/test_avro_schema.py
This PR validates default values in avro schemas as postprocessing after parsing the schema.
=> RFC: validate defaults

karapace/avro_compatibility.py, karapace/compatibility/__init__.py, karapace/compatibility/jsonschema/checks.py, mypy.ini
This tries to make the error message a bit more informative, users may be unaware that the lack of a property in a schema means that any value is acceptable.
I also sneaked a mypy config in there, just to get that rolling.
=> Improved error message for the addition of a property to an open model

karapace/kafka_rest_apis/__init__.py, karapace/serialization.py, karapace/utils.py, tests/integration/conftest.py
Fix compatibility with aiohttp >= 3.8.0 and aiokafka >= 0.7.0
Removed the loop parameter and let python use its default behavior.
Deferred the creation of the client to the first async function that needs it.
This might be a problematic approach if `utils.Client` is a public API and
can't have its `client` parameter removed.
SchemaRegistryClient didn't need to force the `client` value since it was
equivalent to the default.
While the `aiohttp.ClientSession` doesn't require the factory function
to be async, the `aiohttp_client` used during tests needed it.
=> fix compatibility with aiohttp >= 3.8.0 and aiokafka >= 0.7.0

karapace/rapu.py, tests/integration/test_rest.py
This error is expected and should be a client error instead of 500.
If the client POSTs a request body that is too large, we catch the internal aiohttp and wrap it into a client facing user error response instead of returning a internal server error response.
=> karapace/rapu: handle HTTPRequestEntityTooLarge in rapu

karapace/schema_reader.py, tests/integration/test_schema.py
This reverts PR #284 , That was introduced to fix a memory leak, however, it breaks _schemas topics with corrupted data. For now reverting the commit, later the new behavior may be introduced under a flag.
=> Revert release global ids

karapace/karapace.py, karapace/karapace_all.py
Shutdown handler for aiohttp Application was set only for
KarapaceAll. On some environments where REST application and
schema registry application is run separately, e.g. containers,
the shutdown times out and container manager sends kill signal.
Fix is to move the shutdown handler registration from KarapaceAll
to KarapaceBase.
=> Fix REST and schema registry shutdown

.github/workflows/container.yml, README.rst, container/docker-compose.yml
Build container image automatically from the main branch commits with `develop` tag and versioned container images from version tags, including `latest` tag pointing to most recent release.
This used GitHub Container Registry instead of Docker Hub.
Usage of GitHub Container Registry integrates better with tooling, and fetching container images from GHCR is as easy as Docker Hub.
Usage of `latest` tag from most recent release tag requires linear release strategy. If a need to maintain multiple branches arises, this needs some adjustments.
I've also tested building container images in my forked repository by using both main branch and arbitrary release tags there, see https://github.com/tvainika/karapace/pkgs/container/karapace
=> Build container image in GitHub Action

.flake8, .github/workflows/tests.yml, .pylintrc, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/karapace.py, karapace/master_coordinator.py, karapace/protobuf/encoding_variants.py, karapace/protobuf/io.py, karapace/protobuf/protobuf_to_dict.py, karapace/protobuf/syntax_reader.py, karapace/protobuf/utils.py, karapace/rapu.py, karapace/schema_reader.py, karapace/serialization.py, requirements-dev.txt, requirements.txt, setup.py
Updates to support testing and running Karapace using Python 3.10
Mostly this requires updating some lint packages to fix problems they had with the latest version of Python. And then the updated versions of the linters found some different problems to fix or ignore.
=> Add support for Python 3.10

requirements.txt
Avoids CVE-2021-33503 in urllib3 dependency.
=> Update requests to 2.27.1

karapace/protobuf/exception.py, karapace/protobuf/syntax_reader.py, tests/unit/test_proto_parser.py
It seems the attribute `message` is not used anywhere. Changing the constructor signature to match the base class.
=> Simplified exception constructors

karapace/protobuf/enum_constant_element.py
This is the only class not using the dataclasses module, for consistency it should also be based on the std library.
=> protobuf: using standard library dataclasses

.git-blame-ignore-revs
Add `.git-blame-ignore-revs` with the commit that formatted the code using black.
=> git: added .git-blame-ignore-revs

karapace/protobuf/extensions_element.py
- No longer raising AssertionError but instead ValueError, with an error
message
- Iterating directly over the list of elements instead of the indexes
- Simplified value formatting
=> protobuf: simplified ExtensionsElement.to_schema

karapace/karapace.py, karapace/schema_registry_apis.py
The resources for the schema registry server don't need None handling.
=> Schema registry simpler init

karapace/config.py, karapace/kafka_rest_apis/__init__.py
The aiokafka producer has internal batching, the REST API doesn't need multiple producers to work properly
=> REST API single producer

.pylintrc, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/master_coordinator.py, karapace/protobuf/exception.py, karapace/rapu.py, karapace/schema_backup.py, karapace/schema_reader.py, karapace/schema_registry_apis.py, karapace/serialization.py, karapace/utils.py, mypy.ini, requirements.txt, tests/conftest.py, tests/integration/conftest.py, tests/integration/schema_registry/test_jsonschema.py, tests/integration/test_master_coordinator.py, tests/integration/test_rest_consumer.py, tests/integration/test_schema.py, tests/integration/test_schema_backup.py, tests/unit/test_avro_compatibility.py, tests/unit/test_serialization.py, tests/utils.py
While investigating performance issues with the REST Proxy API I took a profile using `py-spy`, the profiler shows the cost of deepcopy is significant for the produce endpoint. This PR replaces the use of `copy.deepcopy` with a faster version based on `ujson`, at the same time replaces all usages of `json` with `ujson`.
Using stdlib's deepcopy:
Using the ujson deepcopy:
The commit also contains a small timeit script to compare the performance of the two implementations.
=> Optimize deepcopy

README.rst, karapace.config.json, karapace/protobuf/io.py, karapace/schema_reader.py, karapace/serialization.py, tests/unit/test_serialization.py
Use configured protobuf runtime directory
Fix `protobuf_runtime_directory` configuration handling to pass configured value around instead of falling back to defaults.
=> Use configured protobuf runtime directory

karapace/protobuf/io.py
Fix protobuf_runtime_directory absolute directory
Related to #348
Invocation of `protoc` failed if `protobuf_runtime_directory` was configured as absolute directory instead of relative subdir.
Change current working directory for `protoc` invocation to have all relative to configured directory to get inputs and outputs there.
=> Fix protobuf_runtime_directory absolute directory

karapace/rapu.py
this is how the error manifest itself in the tests:
```
____________________________________________________________ test_remote_client_protobuf[pyloop] _____________________________________________________________
[gw1] linux -- Python 3.8.12 /home/hacka/work/karapace-venv-3.8/bin/python3.8
tests/integration/test_client_protobuf.py:13: in test_remote_client_protobuf
sc_id = await reg_cli.post_new_schema(subject, schema_protobuf)
reg_cli    = <karapace.serialization.SchemaRegistryClient object at 0x7f4391343fd0>
registry_async_client = <karapace.utils.Client object at 0x7f439122e7f0>
schema_protobuf = TypedSchema(type=PROTOBUF, schema=syntax = "proto3";
package com.codingharbour.protobuf;
option java_outer_classname = "SimpleMessageProtos";
message SimpleMessage {
string content = 1; …
```
=> rapu: internal servel error returns a JSON response

karapace/avro_compatibility.py, karapace/schema_reader.py, karapace/schema_registry_apis.py, karapace/serialization.py, requirements.txt, tests/integration/test_schema.py, tests/unit/test_avro_compatibility.py, tests/unit/test_serialization.py
Bump Python Avro dependency to upstream 1.11.0 from forked and patched version.
Changes in this PR mainly consist of using 1.11.0 Avro API's.
Backwards compatibility study:
* Enum type defaults are not validated in 1.11.0, same behavior as with 1.10.x. This will be validated in version 1.11.1 and resulting exception will be `avro.errors.InvalidDefault: Enum default 'B' is not a valid member of symbols '['A']`. A test is added for this in. This test will fail with 1.11.1.
* With default values on fields accepting null the validation is similar with 1.11.0 as with 1.10.x. Following schema is parsed fine: `{"type": "record", "name": "test_record", "fields": [{"type": ["null", "int"], "name": "test_default", "default": "null"}]}` See that value `"null"` does not conform with the field type …
=> Bump Avro library to 1.11.0

tests/integration/conftest.py
Otherwise while running in parallel the nodes will join the same group, and cause flakiness.
Example of failure:
```
ERROR    Karapace:rapu.py:335 Internal server error
Traceback (most recent call last):
File "/home/hacka/work/karapace-venv-3.8/lib64/python3.8/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
File "/usr/lib64/python3.8/asyncio/base_events.py", line 1025, in create_connection
raise exceptions[0]
File "/usr/lib64/python3.8/asyncio/base_events.py", line 1010, in create_connection
sock = await self._connect_sock(
File "/usr/lib64/python3.8/asyncio/base_events.py", line 924, in _connect_sock
await self.sock_connect(sock, address)
File …
```
=> Registries must use different group ids

setup.py
Use only non-versioned dependencies in `setup.py` in unified fashion for all dependencies, and leave version dependencies to locking file (`requirements.txt`)
References: #342
Use `requirements.txt` for pinning recent good versions, and remove partial CVE listings and minimum requirements lagging behind.
This also allows usage of system dependencies where `requirements.txt` dependencies is not in use, for example Fedora 34, which has `python3-protobuf v.3.14` with a patch for referred CVE.
=> Use only non-versioned dependencies

container/Dockerfile
Fix protobuf in container image
Noticed while doing local test testing for #359. Also noticed that some integration tests cannot be run against separately started Karapace instance, most notably https://github.com/aiven/karapace/blob/6c818230eeefef2b0e629f9ed71270c2b51b81ef/tests/integration/test_rest.py#L182 due not suitable fixture.
Create directory for internal use inside container image and install required dependencies to support Protobuf with the container image.
=> Fix protobuf in container image

karapace/kafka_rest_apis/__init__.py, karapace/utils.py, tests/integration/test_rest_consumer.py, tests/unit/test_serialization.py
Deepcopy uses most of the CPU currently when publishing to a topic. 
Deepcopy is not necessary. So not doing it. Do one shallow copy where it matters (reading from dicts is async thread safe in Python anyway, so reusing same structure without making copy of it should be fine).
=> perf: Skip deepcopy

karapace/kafka_rest_apis/__init__.py, tests/integration/test_rest.py
Handle incompatible schemas with produce endpoint
Produce message endpoint takes full schemas with the message in some cases, and registers the schema during producing the message.  Produce endpoint needs to handle also case if the schema is not compatible with a valid error message.
=> Handle incompatible schemas with produce endpoint

karapace/compatibility/__init__.py, karapace/schema_models.py, karapace/schema_reader.py, karapace/schema_registry_apis.py, karapace/serialization.py, mypy.ini, tests/integration/test_client.py, tests/integration/test_client_protobuf.py, tests/schemas/json_schemas.py, tests/unit/conftest.py, tests/unit/protobuf/test_protobuf_schema.py, tests/unit/test_avro_compatibility.py, tests/unit/test_serialization.py
The schema topic may contain schemas that are invalid by later versions of Avro. The schema models are separated to validated model and non-validated.
Non-validated model is used as storage model. Validated model is used when new schemas are published and on compatibility checking.
This change allows Karapace to start up and serve schemas when invalid/unparseable schemas are present in the storage.
The schema parsing and validity is done when adding new schema. The data present in the schemas topic has passed
validation in the past. Although the schema parsing may have had defects and invalid schemas can be present.
The existence of such data should not prevent Karapace to function and serve these schemas.
=> Handle schema message as string from schemas topic

karapace/utils.py, tests/integration/conftest.py, tests/integration/test_schema_backup.py, tests/utils.py
I'm moving an utility class from the testing to the main codebase
The motivation was this comment from @mhoffm-aiven https://github.com/aiven/karapace/pull/364#issuecomment-1081810314, the idea is to re-use that util to do the timeout and reply with a 204.
I have not changed the APIs to actually return `204` because I found some issues, for example, the delete API sends multiple messages per request:
https://github.com/aiven/karapace/blob/f2746bb925a7687f24115c244ef517c36769618f/karapace/schema_registry_apis.py#L492-L499
So that needs some additional work, instead of having everything in a single PR I'm opening this separately so that it is easier to review.
=> Expose Expiration class

.pylintrc, karapace/config.py, karapace/karapace_all.py
As the title says, docs: https://pylint.pycqa.org/en/latest/user_guide/message-control.html?highlight=enable#detecting-useless-disables
=> pylint: enable useless-suppression

karapace/client.py, karapace/rapu.py, karapace/schema_models.py, karapace/schema_registry_apis.py, karapace/serialization.py, karapace/utils.py, mypy.ini, tests/integration/conftest.py, tests/integration/schema_registry/test_jsonschema.py, tests/integration/test_client.py, tests/integration/test_rest.py, tests/integration/test_rest_consumer.py, tests/integration/test_schema.py, tests/integration/test_schema_backup.py, tests/integration/test_schema_protobuf.py, tests/utils.py
Notes:
- Replaced stdlib's json with ujson in the `json_encode`, should be faster
- I simplified some function signatures:
- removed keyword argument that have a default and were never used by any caller
- remove keyword arguments that have a default, and were always given the same value as the default
- Moved the Client code to a separate module and add typing. Also simplified it by:
- Remove the fallback code that used requests, turns out that `_get_client` always returned a client, so that was dead code
=> Typing and simplification of the utils module

karapace.config.json, karapace/config.py, karapace/karapace_all.py, karapace/rapu.py, karapace/utils.py
Take 2 of https://github.com/aiven/karapace/pull/345
`aiohttp.access` logs can be numerous should clients be constantly
talking to `karapace`, and often these access logs don't provide
significant value for operators.
In order to not throw the baby out with the bath water, this set of
changes allows the use of a logger that outputs `aiohttp.access` logs as
`DEBUG` instead of `INFO` statements. Log filtering can then be applied
at log collection to drop the `DEBUG` logging.
This is really the only way to modify the log level that
`aiohttp.access` logs are emitted at, as `aiohttp` only lets you
totally disable them otherwise. This lets us optionally keep the logs.
An aggregated log would be ideal, but unfortunately the architecture
of `aiohttp` precludes this.
=> logging: add optional aiohttp.access debug logger

karapace/karapace.py, karapace/schema_registry_apis.py
The lock is used only internally by the schema_registry
=> schema_registry: made lock private

setup.py
After Avro version bump the library name is `avro`.
Also `ujson` is missing from the required libraries in `setup.py`.
Karapace uses both, `requirements.txt` and `setup.py`.
=> Fix setup py to use avro instead of avro-python3

karapace/config.py, karapace/karapace.py, karapace/karapace_all.py, karapace/rapu.py, karapace/schema_registry_apis.py, tests/integration/utils/process.py, tests/utils.py
This PR has a few varied changes for issues I found while fixing the tests.
The biggest change is to remove the dead code from RestApp. It currently supports SOCKS requests, which is never used, and it contains two sessions, one with SSL validation and another without, only the one with validation is used.
I'm not sure if this was introduced while working on a feature but it was not finished. For now I'm removing it because I'm seeing SSL validation errors, and that reduces the number of things I need to check to fix that.
There is also some other small changes, for issues I found while debugging.
=> Cleanup rest app

.github/workflows/tests.yml, karapace/client.py, karapace/compatibility/jsonschema/checks.py, karapace/compatibility/protobuf/checks.py, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/admin.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/karapace.py, karapace/karapace_all.py, karapace/master_coordinator.py, karapace/protobuf/io.py, karapace/schema_backup.py, karapace/schema_models.py, karapace/schema_reader.py, karapace/serialization.py, karapace/statsd.py, karapace/utils.py, requirements-dev.txt, tests/integration/conftest.py, tests/integration/test_master_coordinator.py, tests/integration/test_schema.py, tests/integration/test_schema_backup.py, tests/integration/test_schema_backup_avro_export.py, tests/integration/utils/cluster.py, tests/integration/utils/network.py, tests/utils.py
Merge after https://github.com/aiven/karapace/pull/391 (It fix port allocation for integration tests)
Logging schemas has two problems (1) It is cpu intensive, and this is a problem while starting Karapace against a topic with a couple of thousands of schemas (2) Schemas are private information, and this changes the logging with them to `TRACE` level instead of `DEBUG`.
This also makes some logger instances private.
=> Reduced logging

karapace/schema_backup.py, karapace/schema_reader.py
Review after https://github.com/aiven/karapace/pull/391 (It fix port allocation for integration tests)
These are the main changes here:
- If creating the `Consumer` fails, the loop should wait a bit, just like it was done for the `AdminClient`.
- The motivation for this was a hot loop where Karapace was constantly failing to run inside docker, because it could not resolve the hostname. I'm not sure what caused that bug, but I wanted to remove the hot loop (I have the feeling the hotloop is inside kafka-python library, but this one should be fixed anyways)
- The `close` of the consumer should be called even if the `close` of admin client fails
- Instead of using a flag now it uses an Event to stop the thread. It will be faster to stop an uninitialized thread that is doing a retry.
Also:
- …
=> Schema reader loop improvements

karapace/schema_registry_apis.py, tests/integration/test_schema.py
After refactoring schema storage to use non-parsed versions an
error was introduced to schema comparison when posting to subject.
The original Avro schema string can differ from the parsed schema, e.g.
names are not necessary for comparison. Example below:
Stored schema string: {"type":"int","name":"example_name"}
-> parsed schema: "int"
New schema posted to subject: {"type":"int"}
-> parsed new schema: "int"
=> Correct schema comparison when posting to subject

karapace/kafka_rest_apis/__init__.py, karapace/karapace.py, karapace/karapace_all.py, karapace/rapu.py, karapace/schema_registry_apis.py, tests/integration/test_karapace.py
~Review after https://github.com/aiven/karapace/pull/389 (It does a bit of refactoring to the cleanup code), and https://github.com/aiven/karapace/pull/391 (It fix port allocation for integration tests)~
Just like https://github.com/aiven/karapace/pull/389 I found this while investigating the CI failures.
The test `tests/integration/test_master_coordinator.py::test_schema_request_forwarding`  had a server failures, where one server couldn't bind to the socket because of `address already in use` (I assume it was a linger socket). Because of that the main thread died, but the other threads kept running, and the worst one was the master coordinator, eventually the dead server became leader. The result was a leader node without a server, and when the follower forwarded the request to the …
=> karapace: using context manager to ensure all resources are closed

.pylintrc, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/master_coordinator.py, karapace/protobuf/exception.py, karapace/rapu.py, karapace/schema_backup.py, karapace/schema_models.py, karapace/schema_reader.py, karapace/schema_registry_apis.py, karapace/serialization.py, karapace/utils.py, mypy.ini, requirements.txt, setup.py, tests/conftest.py, tests/integration/conftest.py, tests/integration/schema_registry/test_jsonschema.py, tests/integration/test_karapace.py, tests/integration/test_master_coordinator.py, tests/integration/test_rest_consumer.py, tests/integration/test_schema.py, tests/integration/test_schema_backup.py, tests/integration/test_schema_backup_avro_export.py, tests/unit/test_avro_compatibility.py, tests/unit/test_serialization.py, tests/utils.py
Remove `ujson` dependency. After refactoring of deepcopy optimizations the ujson is not needed.
=> Remove ujson dependency

tests/integration/utils/kafka_server.py
Fix logging in integration tests, which causes failure if log level enabled
=> Fix test logging for Kafka download

karapace/kafka_rest_apis/__init__.py, tests/integration/conftest.py
Asyncio locks need to be attached to correct thread. If locks are created in constructor the loop is not available, instead init locks from `aiohttp.web.Application` startup callback.
When calling produce API from REST proxy the first requests fail as the lock acquire future is attached to main loop.
=> Init asyncio locks when event loop is available

karapace/kafka_rest_apis/consumer_manager.py
The error message tell whether the failure was when deserializing key or value. Log the requested format.
Add a dedicated error message for key and value deserialization error and log the requested type. This helps the end user to see what exactly failed.
=> Improve deserialization error message

karapace/anonymize_schemas/anonymize_avro.py, tests/integration/test_schema_backup_avro_export.py, tests/unit/anonymize_schemas/test_anonymize_avro.py
This is useful for later validation of anonymized schemas: prevents hiding invalid characters behind hashes.
=> Preserve invalid characters during schema anonymization

karapace/kafka_rest_apis/__init__.py, performance-test/README.rst, performance-test/rest-proxy-post-topic-test.py, performance-test/rest-proxy-post-topic-test.sh, requirements-dev.txt, tests/integration/test_rest.py
The original implementation waited asynchronously the result of a single producer send. The HTTP request may contains multiple records to be sent in a list. After this change records are sent first and results collected in subsequent loop.
The send function may block until there is free buffer in Kafka producer.
The first commit contains a performance test with Locust to measure the difference of the original implementation and new.
Test creates a HTTP request with 50 records with small payload to be produced to Kafka.
Results from a local test run:
* *Original* -> 12 RPS (12 * 50 records = 600 records / second)
* *New* -> 240 RPS (240 * 50 records = 12000 records / second)
=> Rest proxy produce future handling fix

karapace/schema_reader.py, karapace/schema_registry_apis.py, performance-test/README.rst, performance-test/run-locust-test.sh, performance-test/schema-registry-schema-post.py
Fast path check of schema existence on subject, based on hash of subject and schema string.
Why this way
==========
* The schema, subject pairs are hashed to key for getting schema id, this avoids version list iteration and comparison of input schema to each one in the list like in the original code.
* The schema existence on subject can be done without locking, this is the fast path.
* If schema is not found a lock is acquired and existence is rechecked.
* If schema is found the id is returned, concurrently another request has POSTed the schema.
* If schema is not found after second round of checks it is a new schema.
The round-trip to wait the schema message to be sent to Kafka and receiving it in the schema reader is the longest path and during this time the schema write operation is …
=> Performance: schema string hash to schema id

tests/conftest.py, tests/integration/conftest.py
Fix pytest options handling for running the tests against external
Kafkas, Schema Registries and REST URIs.
Before this using `--kafka-bootstrap-servers=KAFKA_BOOTSTRAP_SERVERS` failed option validation against default value for `--kafka-version`, and yielded `registry_cluster` with externally configured registry was not valid as the configured string was directly returned instead of real `RegistryDescription` structure
=> Fix tests against external kafka, sr, and rest

karapace/schema_registry_apis.py, tests/integration/test_schema.py
Fix subject name escaping
Handle special characters in subject name by using proper JSON formatting.
=> Fix subject name escaping

karapace/kafka_rest_apis/__init__.py
add support for SASL options 
```log
Starting Karapace REST API
2022-07-07T23:43:07.483936981Z karapace            	MainThread	ERROR   	Internal server error
2022-07-07T23:43:07.483987048Z Traceback (most recent call last):
2022-07-07T23:43:07.483996815Z   File "/usr/local/lib/python3.9/dist-packages/karapace/rapu.py", line 324, in _handle_request
2022-07-07T23:43:07.484010202Z     data = await callback(**callback_kwargs)
2022-07-07T23:43:07.484017155Z   File "/usr/local/lib/python3.9/dist-packages/karapace/kafka_rest_apis/__init__.py", line 414, in topic_publish
2022-07-07T23:43:07.484024820Z     await self.publish(topic, None, content_type, request.content_type, request.json)
2022-07-07T23:43:07.484031988Z   File "/usr/local/lib/python3.9/dist-packages/karapace/kafka_rest_apis/__init__.p …
```
=> [FIX] producer sasl support

karapace/errors.py, karapace/karapace_all.py, karapace/master_coordinator.py, karapace/schema_models.py, karapace/schema_registry.py, karapace/schema_registry_apis.py, karapace/typing.py
The `karapace/schema_registry_apis.py` contained application logic
which is mostly moved to module `karapace/schema_registry.py`.
The API controller is now responsible of mapping the requests,
responses and authentication/authorization.
=> Remove schema registry logic from API controller to module

karapace/schema_registry_apis.py
Basically, it allows readonly users to call subjects/subject endpoint. 
References: [#431](https://github.com/aiven/karapace/issues/431)
Not sure whether this is a proper way, but `subjects_schema_post` seems not to change anything. For me it looks like the reason why it requires `Write` permission is because the method goes through POST.
=> Allow subjects/subject endpoint to be called by user with Read permissions

karapace/schema_registry_apis.py, tests/integration/test_schema.py
Fix for issue #428
JSON schema comparison was not validated correctly and threw a  “Schema not found” error when posting to a subject.
Posting a JSON schema
```
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schemaType": "JSON", "schema": "{\"type\": \"string\"}"}' \
http://localhost:8081/subjects/local/versions http://localhost:8081/subjects/local
{"id": 1}{"id": 1, "schema": "{\"type\": \"string\"}", "schemaType": "JSON", "subject": "local", "version": 1}
```
Before
```
curl -X POST -H "Content-Type: application/vnd.schemaregistry.v1+json" \
--data '{"schemaType": "JSON", "schema": "{\"type\": \"string\"}"}' \
[http://localhost:8081/subjects/jsontype-string/](http://localhost:8081/subjects/jsontype-string/)
{"error_code": 40403, "message": "Schema not …
```
=> Fix JSON schema comparison when posting to subject

karapace/schema_registry_apis.py, tests/integration/test_schema.py
[PM-2036]
Fix for issue #435
The issue only occurs when we change the compatibility level for a subject. The fix is to remove the compatibility information from the GET API response.
[PM-2036]: https://aiven.atlassian.net/browse/PM-2036?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove the compatibility level information from the GET API response.

karapace/schema_backup.py, tests/integration/test_schema_backup_avro_export.py
The JSON formatted schema in the message value must be encoded as string. The anonymized data is not parseable when restored by Karapace.
=> fix: encode schema as str on anonymization

karapace/schema_backup.py, tests/integration/test_schema_backup_avro_export.py
The DELETE_SUBJECT message value contains subject property and this field was not anonymized.
=> fix: Anonymize delete subject value on export

karapace/karapace_all.py
For debugging purposes, it's useful to know Karapace conf file. In a typical prod env, the logs are available, but the conf files are not. Thus it'd be useful to dump conf to log. There are passwords in the conf. They must not be logged as such.
=> Log config on startup

karapace/key_format.py, karapace/schema_reader.py, karapace/schema_registry.py, karapace/utils.py, tests/base_testcase.py, tests/integration/test_schema_reader.py, tests/unit/test_key_format.py
Prefer the canonical format on new installations and migrations from
Confluent Schema Registry.
Prefer Karapace key format on installations where this key format use
is detected. This applies to Karapace installations and installations
that have migrated from Confluent Schema Registry to Karapace and have
mixed key formats in schemas topic.
=> feature: detect message key format to use

karapace/schema_registry_apis.py, tests/integration/test_schema.py
There was no mapping to `SchemasNotFoundException` in the compatibility check API controller.
=> fix: return 404 when compatibility check done to non-existent version

karapace/statsd.py, requirements-dev.txt, requirements.txt, setup.py
Removed aiohttp_socks and python_socks.
Moved aiohttp to direct dependencies.
Moved lz4 and requests to indirect dependencies.
Added python-snappy and zstandard to indirect dependencies as those
were in the setup.py for enabling these compression algorithms.
StatsClient comments for ignored exception in Sentry config also cleaned.
=> Clean dependencies

README.rst, karapace/protobuf/schema.py, karapace/schema_reader.py, tests/integration/test_schema_protobuf.py
Fix ProtoBuf schema duplication depending on whitespaces of definition. This was regression as explained on #442.
Compare ProtoBuf schema definitions as normalized strings instead of ProtobufSchema objects to correctly equalize ProtoBuf definitions with minor whitespace differences.  Also for hashing use canonized form of ProtoBuf definition.
Fixes #442
This is alternative approach to PR #445
=> Fix ProtoBuf schema comparison

karapace/schema_models.py
Cache normalized string representation
Some use cases calculate hash of `TypedSchema` multiple times for fast
comparison.  Cache normalized string form of AVRO & JSON Schemas
similar to ProtoBuf for performance improvement.
This might need some follow-up later to use normalized forms of schemas more consistently.
=> Cache normalized string representation

version.py
Karapace releases are lightweight tags. Without `--tags` switch only annotated tags are searched.
Current version is always `2.0.1-747-g3e554f0`, after using `--tags` the version uses correctly the last release tag.
E.g. after the change `3.3.2-5-g9516d08`.
=> fix: Use `--tags` to find last version from Git repository

karapace/key_format.py
Fix writing in detected keymode for key formatting
The bug was in original implementation in #446. The regression seems to have happened during the development of the feature as originally opened PR did not have this issue.
Optional keyword argument was taking over detected keymode in `format_key` method (just some lines below changed function definition).
=> Fix writing in detected keymode

karapace/serialization.py, tests/integration/test_rest.py
Fix REST producing using AVRO primitive schema
In AVRO primitive schemas don't have namespace.  Fix producing AVRO message with REST API when using primitive schema.
=> Fix REST producing using AVRO primitive schema

karapace/kafka_rest_apis/__init__.py, tests/integration/test_rest.py
Fix REST produce handling of invalid request
Posting invalid REST produce request caused intenal server errors with assumptions regarding encoding of records.  Fix content handling and response with valid error messages.
=> Fix REST produce handling of invalid request

.pylintrc, README.rst, karapace.config.json, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/admin.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/serialization.py, tests/integration/conftest.py, tests/integration/test_rest.py, tests/integration/test_rest_consumer.py, tests/unit/test_protobuf_serialization.py, tests/unit/test_rest_auth.py, tests/unit/test_serialization.py
Delegates REST caller principal to Kafka for authorization inside Kafka.
Delegation of caller makes it possible for Kafka to check authorization of REST API caller using already existing Kafka ACL entries & principals.
=> Kafka authorization over REST proxy

karapace/config.py, karapace/karapace_all.py, karapace/rapu.py, karapace/schema_reader.py, karapace/sentry/__init__.py, karapace/sentry/sentry_client.py, karapace/sentry/sentry_client_api.py, karapace/statsd.py, requirements-dev.txt, setup.py
The Raven client is obsolete. Some refactoring is included to
separate the Sentry usage from StatsClient. StatsClient will use
either no-op Sentry client or actual Sentry client is Sentry SDK
is installed.
The Sentry SDK version to be greater than or equal to 1.6.0.
=> Use Sentry SDK

karapace/schema_registry_apis.py, tests/integration/test_schema.py
Iterate schema data retrieved for subject.
=> fix: schema list endpoint to iterate subject schemas

.github/workflows/tests.yml
Current integration tests timeouts frequently as tests take ~10 minutes.
=> Karapace integration tests 15 minute timeout for GitHub Actions

karapace/schema_reader.py, tests/unit/test_schema_reader.py
Karapace relied on poll to return empty topic-messages dictionary and set the state to ready. This PR changes the logic to follow the highest known offset for readiness. When highest offset is catched, state is set ready.
Beginning offset is also tracked in startup. This is to handle case where compaction or purging has removed offset `0`.
=> Decide startup readiness based on the highest record offset

.github/workflows/tests.yml, karapace/schema_registry_apis.py, requirements-dev.txt, requirements.txt
Python 3.11 released, add it to tested Python versions.
https://github.com/actions/runner-images/issues/6459
Github Action test workflow will install `libsnappy-dev` as `python-snappy` with Python 3.11 will fail buildin, no wheel available yet.
Changed to use the value of `SchemaType` enum as Python 3.11 will render `SchemaType.AVRO` instead of `AVRO`.
Dependencies upgraded with Python 3.11 compatible versions. No major changes apart of Python 3.11 compatibility based on the release notes of the libraries.
* aiohttp 3.8.3 (was 3.8.1)
* frozenlist 1.3.1 (was 1.3.0)
* yarl 1.8.1 (was 1.7.2)
* locust 2.13.0 (was 2.9.0) (used in perfomance tests)
=> build: Add Python 3.11 to CI build matrix

karapace/sentry/sentry_client.py
Ignore library logged errors in Sentry
Ignore sending library logged errors to Sentry.  Errors sent currently are such as authentication failures or connection errors, which return or raise also to the calling code, which should handle those per case.
=> Ignore library logged errors in Sentry

karapace/karapace.py, karapace/rapu.py, karapace/schema_registry.py, karapace/schema_registry_apis.py, tests/unit/test_schema_registry_api.py
When Karapace is not ready and still replaying the state from `_schemas` the instance should forward every request to primary node.
=> feature: forward requests to primary node when not ready

.pre-commit-config.yaml
Changes flake8 pre-commit hook to use Github repository instead of Gitlab, [which has been deleted](https://github.com/PyCQA/flake8/issues/1737).
Installing from Gitlab was failing, [PyPI package](https://pypi.org/project/flake8/) points to Github repository and not Gitlab, according to [this pinned issue](https://github.com/PyCQA/flake8/issues/1737), the Gitlab repository has recently been deleted after being obsolete for many years.
=> chore: Update to get flake8 from Github

README.rst, karapace/config.py, karapace/kafka_rest_apis/consumer_manager.py
Fix asynch fetch polling without delay in REST proxy
This is regression from #423 when REST consumer was ported from kafka-python to aiokafka.
Fixes #488
First fetch min bytes negative values was misconfiguration even for kafka-python earlier, but worsened with aiokafka.  Add extra configuration for aiokafka timeout settings tuning.
=> Fix asynch fetch polling without delay

.pre-commit-config.yaml, mypy.ini
Bumps mypy to latest version, 0.991.
Config for mypy is moved from the pre-commit hook definition to mypy.ini, and in addition `pretty = True` is set to show more human friendly error messages.
Keep project up-to-date.
=> chore: bump mypy, move config from pre-commit

website/source/_templates/header-links.html
This link is not needed at the moment so we can get rid of it.
=> website: remove community link from header

karapace/master_coordinator.py, mypy.ini, tests/integration/test_master_coordinator.py
Group coordinator leader is selected from the whole set of members of the group. This can also be member that is not primary eligible. This change corrects the group protocol data and Karapace primary selection to use the actual instance configured primary eligibility. The code before used the primary eligibility of the selected group leader which can be false.
=> fix: Karapace instance primary eligiblity added to group protocol

.github/workflows/tests.yml
Set token for arduino/setup-protoc for rate limits
This is a way instructed at https://github.com/arduino/setup-protoc to overcome GitHub rate limits.
=> Set token for arduino/setup-protoc for rate limits

tests/integration/conftest.py, tests/integration/utils/config.py, tests/integration/utils/kafka_server.py
Add tarfile member sanitization to extractall()
This replaces #510 with the formatting following setup & rules.
Closes #510
Fix test code to use CVE-2007-4559 safe tarfile.extractall.
=> Add tarfile member sanitization to extractall()

karapace/compatibility/__init__.py, karapace/schema_models.py, karapace/schema_registry.py, karapace/schema_registry_apis.py, karapace/serialization.py, requirements.txt, tests/integration/test_schema.py, tests/unit/test_avro_compatibility.py
When parsing existing Avro schemas validation for name and enum default is disabled. This is for compatibility as it has been possible to produce data that is not compliant with Avro specification.
Include also changes for future Avro release compatibility:
* Error message format
* new exception in Avro for invalid binary encoding.
The Avro SDK dependency is taken from Aiven fork of Avro. When upstream Avro releases the support for validation disable it is possible to move the dependency back.
=> Disable Avro name and enum validation when parsing existing schemas

karapace/schema_registry.py
This change is needed to avoid the race condition on [this line](https://github.com/aiven/karapace/blob/main/karapace/schema_registry.py#L87) under heavy load.
The dict keys() method return a views on the data that could change during the execution, it is needed a copy of them to avoid "RuntimeError: dictionary changed size during iteration". We can get read of the values as they are not needed in this method.
=> fixed "dictionary changed size during iteration"

.github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/lint.yml, .github/workflows/tests.yml
Node 12 is deprecated and removed soon. This affects multiple GitHub actions.
The Protobuf compiler action is not updated, it is missing the release for Node 16 support.
=> chore: update GitHub action versions

karapace/auth.py
`awatch` disables file watching if a delete event for that file is issued. This may result in the impossibility to read new users and permissions data if the authfile is replaced.
Resetting file watch after delete event allows notifications related to the new file to be received.
=> fix: reset watch of authfile after delete event

.github/workflows/tests.yml
Remove `max-parallel` limitation from test workflow.
The test matrix contains 5 versions, there's really no need to cap parallelism to 4 here. This should make the test suite pass in about half the time as all the jobs can run in parallel.
=> chore: Remove max-parallel from test workflow

.github/workflows/lint.yml, .github/workflows/tests.yml
Disable triggering of test suite re-run when marked ready for review.
Making the test suite re-run when marked ready for review incentivizes against using draft pull request and only marking them ready once the test suite is passing.
=> chore: Disable test suite re-runs on ready for review

.pre-commit-config.yaml, README.rst, pyproject.toml, setup.py
Change execution order of pre-commit hooks. It's a good idea to allow isort to run before black, to let black be authoritative on formatting. The very fast builtin pre-commit checks are moved to top to always execute first.
Some superfluous configuration options are removed, specifically there's no need to point out that Python tools should run on Python files, this is already configured in the hooks themselves.
By default, flake8 uses the .flake8 config file.
Black line-length config is moved from a hard-coded CLI argument to pyproject.toml which is picked up by default, and target-version=37 is added there explicitly.
- 🎉 Advertise support for Python 3.11 with a setup.py classifier.
- 🕵️ Fix a typo in README.
Simplify and improve project config.
=> chore: Simplify pre-commit config

.flake8, .github/workflows/lint.yml, .pre-commit-config.yaml, .pylintrc, karapace/compatibility/protobuf/checks.py, karapace/kafka_rest_apis/__init__.py, karapace/protobuf/protobuf_to_dict.py, karapace/protobuf/reserved_element.py, karapace/rapu.py, karapace/schema_reader.py, karapace/schema_registry.py, karapace/sentry/sentry_client.py, karapace/serialization.py, karapace/utils.py, requirements-dev.txt, tests/integration/test_karapace.py, tests/integration/utils/kafka_server.py, tests/integration/utils/zookeeper.py
Apply `pre-commit autoupdate` and bump CI Python to 3.11, to get isort 5.12.0.
Fix flake8 config.
The fix is opinionated in that it stops running pylint with project dependencies. I considered suggesting to remove usage of pylint entirely, and I still want to suggest that, but that's a discussion we can have separately from fixing CI builds on main.
CI is broken on main due to this isort issue, the root cause lies in an
underlying incompatible change in Poetry. The new version of isort has
dropped support for Python 3.7 so we bump CI to run on 3.11 instead (3.7
is EOL later this year anyway).
https://github.com/PyCQA/isort/issues/2083
With the upgrade to flake8 6, we ran into an issue with comments in the
configuration file. Those comments are moved to their own lines above
the config …
=> fix: Bump pre-commit hooks to fix isort issue

.github/workflows/codeql-analysis.yml, .github/workflows/container.yml, .github/workflows/lint.yml, website/source/install.rst
Fix broken references to previous name of default branch.
Linting isn't currently running on main. CodeQL analysis looks like it hasn't been running for 9 months.
=> fix: Replace references to old default branch name

.github/workflows/lint.yml, .pre-commit-config.yaml, Makefile
Delete the copyright make target and replace it with a pre-commit hook. Remove the Github Action job, as this will now run as part of `lint.yml::lint`.
Fewer moving parts and shorter feedback cycle. _All_ linting can now be run uniformly with `pre-commit run --all-files`.
=> chore: Incorporate copyright check in pre-commit

karapace/schema_backup.py, tests/unit/test_schema_backup.py
The schema backup tool is currently overwriting the output file without asking to do so. It is also writing directly to the output file, and leaves the file intact even if the backup actually failed. This patch adds guards that fail if the output file already exists, but also an `--overwrite` flag. It also introduces a temporary file that is persisted only if the backup actually succeeded, not leaving behind any trace of the work if not.
The output needs to be a file to be overwritten, even with the `--overwrite` flag present. Any other path type is not going to be touched. Our code verifies this, and Python's `replace` function does as well.
Other smaller things worth mentioning:
- The `--location` accepts `-` as synonym for `stdout` as is conventional, the current empty string continues …
=> Add Backup File Overwrite Protection

karapace/compatibility/__init__.py, karapace/schema_registry.py, tests/integration/test_schema.py
Fix Avro enum symbol addition and removal compatibility handling. Karapace has been ignoring those incompatibilities for unknown historical reason.  Improve compatibility result logging to be more informative.
Fixes #524
=> Fix Avro enum compatibility handling

.github/workflows/tests.yml
The integration tests are constantly running into timeouts, requiring manual reruns.
=> Increase Integration Test Timeout

karapace/schema_backup.py, tests/unit/test_schema_backup.py
This adds a check that verifies that the source and target topic for a backup indeed have a single partition, instead of simply assuming that it does. This is not a breaking change, since it makes the implicit explicit, and users who are going to receive the error are going to be protected from a lot of hardship.
This also removes the consumer and producer clients from the class by moving them into dedicated top-level functions. Those top-level functions are context managers that close the clients automatically in a reliable way. This removal could be considered a breaking change, since we are removing public functions from a class. However, these functions were never meant to be public, especially not because they were directly meddling with internal state.
The new top-level functions …
=> Add Backup Partition Count Check

karapace/schema_backup.py
Backup restoration messages that are produced to the restored topic are currently sent in a fire-and-forget fashion. This PR modifies this behaviour, waiting for the produce action to complete and raising an error if the send was not successful. 
An error is raised if the produce action was not successful, allowing the caller to know that something went wrong.
=> Handle errors while producing backup restoration messages

karapace/kafka_rest_apis/consumer_manager.py, karapace/serialization.py, tests/integration/test_rest_consumer.py, tests/utils.py
Currently, failing to deserialize a record to the requested format during consuming results in internal error. Also, json decode error was not caught.
For example: If user has produced binary records to a topic and then tried to consume them using format json. The response would be a 500 internal server error without proper message.
Should now properly catch json decode exception and change exception type from 500 to 422 including the intended message. Also adds test that should help ensure this will happen with all known formats.
=> Add more graceful handling when deserialization fails for a record during consuming

.github/workflows/tests.yml
The protobuf compiler that is being installed in GitHub Actions has a different version than the library that is used by Karapace. To avoid further drift it is necessary to ensure that they stay aligned automatically. This patch adds some code to extract the actual Protobuf version from the `requirements.txt` file.
Note that this approach is going to break with newer Protobuf versions. This is because Google decided to stop versioning all Protobuf dependencies alike. However, newer versions of Python Protobuf do not require the Protobuf Compiler to be installed anymore. Hence, if we upgrade, we can get rid of the Protobuf Compiler installation entirely.
=> Fix GHA Protoc Installation

karapace/schema_backup.py, requirements.txt, tests/unit/test_schema_backup.py
The retry logic in the backup code for admin client and topic creation is flawed as it compares seconds to milliseconds. Instead of aborting after the desired 60 seconds it aborts after 60,000 seconds. The retry implementation itself has several other issues, most notable the fact that it swallows `BaseException`, and thus cannot be interrupted by the user when it enters the retry loop.
Instead of trying to come up with an optimized retry logic or a generic solution that can be used across the board, I decided to add a well tested library that already provides this logic. ~I also use `timedelta` in favor of primitives for all durations, to avoid unit confusion.~ This was reverted, because we have to use an older tenacity version that does not support `timedelta`.
This updates only the …
=> Fix Backup Topic Creation Retries and Interrupts

karapace/schema_backup.py
Allow the backup restoration producer to send messages asynchronously.
If an error arises while producing a message, the exception is raised, causing the process to finish with an exit code of 1.
=> Async backup restoration with error handling

tests/integration/test_karapace.py, tests/integration/utils/cluster.py, tests/utils.py
This removes the hardcoded `python` executable name in tests with a more dynamic approach that resolves to the Python executable used by the tests. Not all systems have Python 3 available at `python` by default, and there is no guarantee that the `PATH` in a `venv` is modified to include the `venv/bin` directory in the `PATH`. Python offers `sys.executable` to find the current executable, if that fails we fall back to the same environment variable we use in our make file, and if that fails we use `python3` (seems to be available on most systems).
=> Fix Python Executable Search in Tests

karapace/backup/consumer.py, karapace/backup/errors.py, karapace/schema_backup.py, requirements.txt, tests/integration/conftest.py, tests/integration/test_schema_backup.py, tests/integration/test_schema_backup_avro_export.py, tests/unit/backup/test_consumer.py
The consumption logic is currently counting how many records it received in a single batch returned from poll, and when it is empty it concludes that the backup is successfully finished. However, there are meany reasons why a batch returned by poll is empty, especially with timeouts applied to it. A consequence of this is that a backup created at $t_1$ may contain more records than a backup created at $t_2$ (without any external changes to the topic content, e.g. compaction).
To fix this we have to use offset watermarks. With them we can determine if we are done, or not. The patch now exposes the poll timeout, so that users can increase it in case they encounter issues, and it uses a longer default poll timeout to ensure that users are not going to see errors right away (increased from 1 …
=> Fix Create Backup Consumption Logic

tests/conftest.py
For some reason some (unit) tests fail occasionally, because the default config file at the time of reading contains incomplete JSON. This adds a flush and sync to the fixture to make certain that the file was written in its entirety to disk before continuing.
=> Fix Flaky Default Config Fixture

.editorconfig, .github/workflows/lint.yml, .pre-commit-config.yaml, container/build_image.sh, container/publish_image.sh, container/start.sh, performance-test/run-locust-test.sh, requirements-dev.txt
This adds `shellcheck` and `shfmt` pre-commit hooks. I fixed the most pressing issues that were found, but did not go through the existing scripts otherwise. We are going to need more shell scripts to automate other things, this is why it is a good idea to add these tools to our verification chain.
~This also changes the GHA lint workflow to use the official pre-commit action, which also makes use of caching, and thus should be faster.~ The pre-commit action uses the `--color=always` option, and that option results in the action hanging forever if paired with local hooks, which we have.
=> feat: Add `shellcheck` and `shfmt` Pre-Commit Hooks

.pre-commit-config.yaml
Remove untracked files from pre-commit copyright header check.
Some times, at least I, have some special purpose scripts that are not tracked and won't be commited. The pre-commit hook then fails for missing copyright headers. This corrects the behavior to select only the files tracked by Git.
=> chore: remove untracked files from copyright header check

karapace/in_memory_database.py, karapace/schema_registry_apis.py, tests/integration/test_schema.py
The subject config endpoints did not return 404 for unknown subjects. A 500 internal error was returned.
=> fix: return 404 for config actions on unknown subjects

karapace/auth.py, karapace/karapace.py, karapace/master_coordinator.py, karapace/rapu.py, karapace/schema_reader.py, karapace/schema_registry_apis.py
Add health status endpoint
Fixes #143
Implement health status endpoint which returns status of schema registry.  This by design avoids long running operations, and queries status from internal state variables acquiring only minimal locks.  This is designed to robustly and quickly return internal status of Karapace.
=> Implement health status endpoint

.pre-commit-config.yaml, copyright.sh
- Change to using regular grep for copyright check.
- Move the check from inline in the pre-commit config to a separate shell file.
- Use pre-commit for file discovery and exclusion.
Fixes #563.
=> fix: Use regular grep for copyright check

requirements.txt
The quoted issue has been fixed in [latest version of watchfiles](https://github.com/samuelcolvin/watchfiles/releases/tag/v0.19.0).
=> Bump dependencies to latest version of watchfiles

karapace/auth.py, karapace/key_format.py, karapace/master_coordinator.py, karapace/schema_models.py, karapace/schema_registry.py, karapace/typing.py, karapace/utils.py
This introduces narrower type aliases to describe JSON-compatible dicts. Because we now have more accurate typing, in some places this reveals places where we are not properly dealing with all possible types that deserialized JSON can have. In order for this PR to not do too much in one go, I opted to introduce `TypedDict`s along with a mechanism to cast directly invocations of `json_decode()`. This reflects the same assumptions we make in runtime onto to our static typing.
We should consider introducing tooling to allow properly deserializing into rich Python types, such as Pydantic or Dacite.
=> Introduce narrower JSON typing

karapace/anonymize_schemas/anonymize_avro.py, karapace/config.py, karapace/key_format.py, karapace/master_coordinator.py, karapace/messaging.py, karapace/schema_backup.py, karapace/schema_registry.py, karapace/utils.py, mypy.ini, tests/unit/test_schema_registry_api.py
- Add type hints to schema_backup.
- Add TypedDict to describe configuration.
- Fix non-functioning overload of json_encode.
- anonymize_avro_schema_message() is updated to adhere to the interface stipulated by SchemaBackup.create(), i.e. must accept None.
=> Add type hints to schema_backup

requirements.txt
The `ghcr.io/aiven/karapace:develop` image is currently failing to start with the following error (for the REST api, but the same thing occurs for registry):
```
karapace-rest_1      | Traceback (most recent call last):
karapace-rest_1      |   File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
karapace-rest_1      |     return _run_code(code, main_globals, None,
karapace-rest_1      |   File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
karapace-rest_1      |     exec(code, run_globals)
karapace-rest_1      |   File "/usr/local/lib/python3.9/dist-packages/karapace/karapace_all.py", line 8, in <module>
karapace-rest_1      |     from karapace.config import read_config
karapace-rest_1      |   File "/usr/local/lib/python3.9/dist-packages/karapace/config.py", line …
```
=> Add missing required module

.pre-commit-config.yaml
This automatically removes unused imports, providing auto-fix for some of the linters that come after (pylint, flake8).
QoL, providing auto-fix for rule enforced by other linters.
=> chore: Add autoflake pre-commit hook

pytest.ini
- Configure pytest to use the recommended "importlib" import mode. https://docs.pytest.org/en/7.1.x/explanation/pythonpath.html#import-modes
https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#choosing-an-import-mode
- Turn all test directories into Python modules.
- Makes a bare `pytest` invocation work as expected.
- Recommended in pytest docs.
- Will enable introducing `src` directory in the future.
- Closer to normal Python import behavior instead of pytest specialness of non-package imports.
=> fix: use pytest's importlib import mode

.github/workflows/container-smoke-test.yml, CONTRIBUTING.md, README.rst, container/Dockerfile, container/compose.yml, container/healthcheck.py, performance-test/README.rst, tests/integration/utils/kafka_server.py, website/source/install.rst
- Rename docker-compose.yml -> compose.yml to adhere to [new standard](https://docs.docker.com/compose/compose-file/03-compose-file/).
- Add `build` configuration to compose file.
- Add smoke testing Gihub Actions workflow.
- Replace `docker-compose` invocations with `docker compose`.
- Add healtcheck to Dockerfile, to enable waiting until services are healthy.
References: #585
=> chore: Add very basic container smoke tests

.github/dependabot.yml
Interestingly, this did not fail on the PR that introduced it, but started failing here: https://github.com/aiven/karapace/pull/583/checks?check_run_id=13200070246
Here's the relevant documentation: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
=> fix: Incorrect package-ecosystem value for dependabot

.github/workflows/container-smoke-test.yml, bin/smoke-test-registry.sh, bin/smoke-test-rest.sh
The newly introduced smoke-test is seemingly flaky, with `HTTP 503` responses from Karapace. This PR introduces retries on failures.
I first attempted to introduce waiting for Kafka to listen, using netcat, as well as waiting for schema registry to respond with `"schema_registry_ready": true` in `/_health`, but saw `503` after both of these. So retrying seems like a more viable solution.
Here's an example of a failing build: https://github.com/aiven/karapace/actions/runs/4872294084/jobs/8690298720?pr=578
=> fix: Make smoke-tests retry on failure

karapace/schema_registry_apis.py, tests/integration/test_dependencies_compatibility_protobuf.py
Fix references validation from request
Handle null as empty list of `references`, and reject wrongly typed values.  Fixes #591
=> Fix references validation from request

karapace/schema_models.py, karapace/schema_reader.py, karapace/schema_registry_apis.py, mypy.ini, tests/integration/test_dependencies_compatibility_protobuf.py, tests/integration/test_schema_protobuf.py
* Include references in responses
* Add support to latest version with references
Both are to better support `references` feature implemented in #560 but missing parts of full references support.
Schema fetch and list operations should contain references if any in the response.
Registering a schema with a reference to version -1 is a reference to latest version of referenced schema.
Also minor cleanups, including eliminating of cached string representation of non-protobuf schemas, which should not have been changed with #560.
=> Improve references support

.dockerignore, .github/workflows/container-smoke-test.yml, .pre-commit-config.yaml, container/Dockerfile, container/start.sh, setup.py, version.py
- Use cache mounts for pip and apt, heavily reducing network requests when cache is warm.
- Remove git as a build-time dependency, other than switching to archive endpoints as was done in https://github.com/aiven/karapace/commit/39b4f0850c3eaa6ef0d41a7b4e152cc4291ab0f3, this also requires either setting `KARAPACE_VERSION` as container build arg or building karapace/version.py independently.
- Add hadolint pre-commit check for linting Dockerfile.
- Move to using Python base images for builder and final stage. This allows omitting installation of some build tools. It also allows moving to a more recent Python version, no longer being bound by what's in distro repositories. Wheel availability of some of our Python dependencies prevents us from moving to 3.11 for now.
- Change installation …
=> Optimize container build time

.github/workflows/tests.yml, pytest.ini
Set `--showlocals` via `PYTEST_ADDOPTS` in CI, instead of setting globally in `pytest.ini`.
`--showlocals` is very verbose, and cannot be disabled without editing `pytest.ini` currently. To allow disabling it locally, while keeping it enabled in CI, it's moved from `pytest.ini` to an env var in CI. It can still easily be enabled on dev machines, either by passing `--showlocals`, or by setting `export PYTEST_ADDOPTS=--showlocals` (and this can be made ergonomic by using a tool like direnv).
=> chore: Set --showlocals in CI env instead of global

karapace/kafka_rest_apis/__init__.py
If `sasl_mechanism` already defined in the config - do not override it with `PLAIN`.
Our Kafka installation allows SCRAM authentication only, so current code leads to failed authentication. Preferred mechanism already stated in the config, so let's use it for the user proxy.
`config["sasl_mechanism"]` default value is `None`, so let's check for it. I'm not sure if we can remove this line completely and rely on that undefined SASL mechanism often means `PLAIN`. This is the most safe patch - keeping existing behavior.
=> fix: do not override SASL mechanism for user REST proxy

.github/dependabot.yml
Change Dependabot schedule to monthly from daily
It is too noisy with daily updates. No need for such frequent updates.
=> Change Dependabot schedule to monthly from daily

karapace/protobuf/compare_result.py, karapace/protobuf/dependency.py, karapace/protobuf/known_dependency.py, karapace/protobuf/one_of_element.py, karapace/protobuf/schema.py, karapace/protobuf/syntax.py, karapace/schema_registry_apis.py, mypy.ini, tests/integration/test_schema_protobuf.py
Validate that referred known types are imported before use.  Also improve typing and mypy purity a bit.
This addresses partially: #626
This is compatible behaviour with other protobuf implementations.
=> Validated imports for known types

.github/workflows/schema.yml, GNUmakefile, karapace/backup/backends/v3/schema_tool.py
- Add fetch-depth 0 to CI job.
- Change logic to accept remote name and pull from it.
Check is currently broken.
Note that this introduces an expectation on how remotes are named, i.e. it expects to be able pull `origin/main`. This seems like an acceptable trade-off to me, and the make target accepts this as a parameter, so one can override it by running `make schema against=upstream/main` locally, if one has named the remote “upstream”.
=> fix: Repair broken schema check

README.rst, karapace/config.py, karapace/kafka_rest_apis/__init__.py, tests/integration/conftest.py, tests/integration/test_rest.py
The REST producer uses default maximum request size of 1048576 bytes. This is now defined explicitly and configuration file allows overriding the value.
=> feat: Add REST producer max request size config

karapace/protobuf/field_element.py, karapace/protobuf/proto_type.py, mypy.ini, tests/integration/test_dependencies_compatibility_protobuf.py, tests/integration/test_schema_protobuf.py
Hard-coded known types do not have message element linked similar to user defined messages.  Handle comparing of those fields without internal errors from exceptions.
Fixes #626
=> Handle message field compare with known types

karapace/backup/poll_timeout.py, mypy.ini, stubs/isodate/__init__.pyi, stubs/isodate/duration.pyi, stubs/isodate/isoduration.pyi, tests/unit/backup/test_poll_timeout.py
Add partial stubs for the isodate library.
This revealed a surprising bug in `PollTimeout`, where we don't handle `parse_duration()` returning `isodate.duration.Duration`.
Increase type coverage.
This is potentially controversial as it only adds partial stubs for the isodate library. This means that the interactions we have currently will now be typed, which is an improvement. But it also means that if someone tries to introduce other valid interactions with the library, that aren't covered by the stubs, it will yield static type checker errors.
The "right" fix when that happens is to expand the partial stubs so that they also cover the new usage, but it's quite hard to make this discoverable, and teach that this is how to fix the issue.
=> chore: Add partial stubs for the isodate library

karapace/backup/api.py, karapace/backup/backends/v3/backend.py, karapace/backup/backends/writer.py, tests/integration/backup/test_v3_backup.py
Instead of using a predefined directory for storing the backup files, `karapace_schema_backup get` should allow to specify the name of the directory where the files will be stored.
=> feature: Allow backup creation to specify target directory

karapace/backup/api.py, karapace/backup/backends/v3/schema.py, tests/integration/backup/test_v3_backup.py, tests/integration/utils/kafka_server.py
- Remove an incorrect assertion on number of data files in `Metadata.__post_init__`. Empty partitions will not have data files.
- Add integration test verifying a full backup-restoration cycle for an empty partition.
=> fix: Broken backup handling of empty topics

karapace/backup/api.py, karapace/backup/cli.py, tests/integration/backup/test_v3_backup.py, tests/unit/backup/test_api.py
With this change, we allow passing the same path of the directory created when producing a backup, into restoration and inspection commands. Together with the fix in 5becdb4b, this makes V3 more similar to V2, in the respect of handling given paths.
Also improves test coverage of some of the helper functions in the internal API.
=> feature: Allow passing backup directory to backup commands

karapace/protobuf/schema.py, karapace/schema_models.py, karapace/schema_reader.py, karapace/schema_references.py, karapace/schema_registry.py, karapace/schema_registry_apis.py, karapace/serialization.py, tests/unit/test_protobuf_serialization.py
First off, this fixes the issue that `Reference` objects were mutated while acting as immutable by implementing `__hash__()`. To do that, it breaks up the `Reference` class into two, so that instead of it having two overloaded meanings, the unresolved state is instead represented as its own entity, `LatestVersionReference`. A `LatestVersionReference` can be converted to a `Reference` by providing a version to its `.resolve()` method. This is a typical "make illegal states unrepresentable" kind of refactoring.
Related to this, a few `list` and `dict`s are replaced with their immutable abstract counterparts, `Sequence` and `Mapping`. This greatly helps in reasoning about where mutation can happen, and stops me from constantly wondering "will this list be altered when I pass this down this …
=> fix: Reduce mutability in schema references

karapace/schema_registry_apis.py, tests/integration/test_schema.py
Fix exception handler after fetching raw schema after delete
Fix exception handling to avoid throwing internal server errors.
=> Fix exception handler fetching raw schema after delete

karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/admin.py, tests/integration/test_rest.py, tests/utils.py
Default partitioner uses random partition if no key is given.  Add test that verifies random partition assignment with time-out.
Internally no key was converted to zero length byte array, which caused kafka library partitioner to handle it differently than no key.
=> Fix partitioning if no key given

tests/integration/test_rest.py
Add a pin-point test for REST proxy when data given in publish request is incompatible with the given schema.
=> test: test incompatible data publish on REST proxy

karapace/kafka_rest_apis/consumer_manager.py, tests/integration/test_rest_consumer.py
Adds `timestamp` to the consumer records response.
Timestamp is already available on the internal response. This implementation is following the same approach as e.g offset.
=> feat(rest:consumer): add timestamp to consumer fetch response

.gitignore, karapace/avro_dataclasses/models.py, karapace/client.py, karapace/in_memory_database.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/schema_cache.py, karapace/schema_registry.py, karapace/schema_registry_apis.py, karapace/serialization.py, karapace/typing.py, requirements/requirements-dev.txt, requirements/requirements-typing.in, requirements/requirements-typing.txt, requirements/requirements.in, requirements/requirements.txt, tests/integration/test_client.py, tests/integration/test_client_protobuf.py, tests/integration/test_rest.py, tests/integration/test_schema.py, tests/unit/test_protobuf_serialization.py, tests/unit/test_serialization.py, tests/utils.py
This pr is ment to fix [this issue](https://github.com/aiven/karapace/issues/658) the test where we try this problem is `test_publish_with_schema_id_of_another_subject`.
The list of subjects bound to a topic has been added to the `/schemas/ids/{id}` if the `{"includeSubjects": "True"}` param are included. This helps the rest proxy in understand if a certain subject when it's required to produce a message providing only the `SchemaID`, once the REST proxy get the Schema and the list of allowed Subjects it calculate the subject and checks if the required subject it's allowed or not.
=> fix: inconsistent schema during message produce

karapace/schema_registry_apis.py, karapace/serialization.py, tests/integration/test_schema.py
The default reply for a schema given it's ID contains the `subjects` field. The default implementation of Jackson it's strict and translate the missing of explicit description of the object in the Java class in an exception, to be precise a `com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "subjects"` exception.
This fix restore the previous design that enable the field only if the `includeSubjects` header with a `true` value it's provided.
=> fix: remove 'subjects' from the default schema reply

.gitignore, karapace/kafka_rest_apis/schema_cache.py, karapace/protobuf/schema.py, karapace/schema_references.py, karapace/serialization.py, tests/integration/test_client.py, tests/integration/test_client_protobuf.py, tests/integration/test_rest_consumer_protobuf.py, tests/unit/test_protobuf_serialization.py, tests/unit/test_serialization.py
The previous implementation of the schema resolver wasn't resolving recursively the entities of a schema that was containing references. With that implementation the schema are recursively resolved and the references are sent to the parser.
Closes #679
=> Resolve schema reference recursively during schema parsing

karapace/protobuf/schema.py, tests/unit/protobuf/test_dependency.py
On nested field with one of restriction the parent name did not include the element name.
This causes the dependency verification to fail as the actual full name of the nested one of field type
was not in the known used types.
=> fix: fix nested one of field handling for protobuf schema dependency verification

.gitignore
#681 added an additional `.gitignore` line for the `runtime/` directory, however, this directory already has a [nested .gitignore](https://github.com/Aiven-Open/karapace/blob/main/runtime/.gitignore).
I think it might be preferable to keep the current nested .gitignore, as otherwise there's nothing stopping removing the `runtime/` directory.
=> fix: respect nested runtime/.gitignore

karapace/kafka_rest_apis/admin.py
API requests to `/topics/<topic>/partitions/<partition_id>/offsets` often lead to `not_leader_for_partition` error as the request goes to the least loaded node. It needs to go to the leader instead.
[HH-2464]
=> fix(rest:offsets): prevent `not_leader_for_partition` error

karapace/config.py
Use `KARAPACE_ADVERTISED_PORT` environment value
Fixes #688
Each configuration setting must be defined in `DEFAULTS` to enable reading those from environment variables.  There was regression with typing causing it to be removed earlier.
=> Use KARAPACE_ADVERTISED_PORT environment value

.github/CODEOWNERS
Migrate CODEOWNERS to new GitHub organization
=> Migrate CODEOWNERS to new GitHub organization

karapace/schema_registry_apis.py, tests/integration/test_schema_protobuf.py
Fix references support in parsing code that checks if a schema has been registered under the specified subject.
Parsing code did not pass parsed references correctly in the check code used by the endpoint.
=> Fix references support in check schema registered endpoint

karapace/kafka_utils.py
Currently in the backup tool we leave implicitly the setting about the retries.
This (if the default value change) could lead to duplication of messages in the restore of a topic.
=> fix: explicitly set retries to 0

karapace/protobuf/dependency.py, karapace/protobuf/schema.py, tests/unit/protobuf/test_protobuf_schema.py
Before this PR the protobuf schema was able to refer only to fully qualified names or names defined in an higher leaf of the parsing tree.
This commit enable a schema to refer the same scope level if at the same leaf level there is defined exactly the field required after.
In an example:
```protobuf
enum FancyEnum {
...
}
message FancyMessage1 {
FancyEnum field ...
}
```
`FancyMessage1` is allowed to call `FancyEnum` because his scope is `/FancyMessage1` while the scope of `FancyEnum` it's `/` (the name itself doesn't count in the declarations, but take part only in field assignment inside the declarations, we could say that `field` has the scope set to `/FancyMessage1` but the type `FancyEnum` has also the scope `/`, only when referring to a type you enter in it's scope during the …
=> fix: enable self-referencing schemas

README.rst, container/compose.yml, website/source/install.rst
Update new container registry location in various places.
Fixes #697.
=> chore: Update container registry URLs

karapace/kafka_rest_apis/consumer_manager.py
With REST authorization enabled, users got http 500 when attempting to consume topics for which they are not authorized.
The change consists in catching the exception TopicAuthorizationFailedError as part of http 403 response. 
References: HH-2806
=> REST proxy to return 403 instead of 500 in case of deny by ACL

README.rst, container/Dockerfile, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/serialization.py, tests/integration/conftest.py, tests/integration/test_rest.py, tests/unit/test_protobuf_serialization.py, tests/unit/test_serialization.py
Fix subject `name_strategy` configuration setting, which we have had kind of documented but not working. Now it is possible to set it, and use it. Also fixes documentation to match what has been the default in the implementation.
Add new configuration option `name_strategy_validation` (true by default) which allows skipping subject name strategy validation when producing messages with Kafka REST calls. 
References: #664 and #724
This enables easy backward compatible behaviour of producing with REST using any schema.
=> Fix subject name strategy config and add validation flag

container/Dockerfile
Fix protobuf-compiler version to match Debian bullseye
=> Fix protobuf-compiler version to match Debian bullseye

README.rst, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/authentication.py, karapace/kafka_rest_apis/consumer_manager.py, mypy.ini, requirements/requirements-dev.txt, requirements/requirements.in, requirements/requirements.txt, setup.py, tests/unit/test_authentication.py, tests/unit/test_rest_auth.py
OAuth credentials pass-through:
* Allow passing through OAuth2 credentials to the underlying Kafka service
* In case the incoming HTTP request's `Authorization` header has a `Bearer` token, will create Kafka clients with the `OAUTHBEARER` SASL mechanism and pass the token through to them
* Basic SASL authentication behaviour is unchanged
* Changes and the addition of the OAuth2 possibility only apply to the REST proxy
Proxy janitor extension:
* The user proxy janitor is extended to clean up proxies with soon-to-be-expired tokens to avoid Kafka clients going into a connection retry-loop until they are cleaned up by existing janitor logic
* Extracting the expiry time from the token doesn't include signature verification - even if the token has been tampered with, Kafka verifies the token …
=> REST proxy SASL OIDC authentication

karapace/kafka_rest_apis/authentication.py, tests/unit/test_authentication.py
Handle JWT DecodeErrors when extracting the expiration timestamp from an OIDC/OAuth2 JWT token, otherwise this would result in an HTTP 500 response.
Catching PyJWT's `DecodeError` is sufficient, as all other exceptions from the library (see
https://pyjwt.readthedocs.io/en/stable/api.html#exceptions) are related to proper verification, which we do not do at the moment.
=> Return Unauthorized on malformed OAuth token

karapace/karapace.py, tests/integration/test_rest.py
- Added the Karapace version to the healthcheck reply
- Added typing in the parameters of the file
=> feat: add version of karapace to the healthcheck response

pytest.ini
Increase pytest verbosity, by removing the quiet flag as well as the `--tb=short` flag.
In this failing CI run, the fact that we use `--tb short` makes it impossible to tell what code path triggered the breaking call to `read_config()`.
https://github.com/Aiven-Open/karapace/actions/runs/6239301084/job/16936931606
=> chore: Make pytest CI runs more verbose

karapace/avro_dataclasses/introspect.py, requirements/requirements-typing.txt
Bumps mypy and fixes revealed problematic code in avro introspection code where wrong entities was used.
Supersedes and closes #747.
=> Bump mypy and fix problems in avro introspection code

README.rst, karapace/config.py, karapace/kafka_rest_apis/__init__.py, karapace/protobuf/schema.py, karapace/schema_reader.py, karapace/serialization.py, karapace/typing.py, tests/conftest.py, tests/integration/test_rest.py, tests/unit/protobuf/test_protobuf_schema_name.py, tests/unit/test_protobuf_serialization.py, tests/unit/test_serialization.py
Before that commit the other strategies where existing but not effectively usable/tested in the codebase.
This pr adds the support and set tests to effectively test the naming strategies.
During the development I've also added a little bit more typing over the files I've touched to improve the codebase
=> Added support to other naming strategy

karapace/protobuf/enum_element.py, karapace/protobuf/location.py, karapace/protobuf/message_element.py, karapace/protobuf/schema.py, karapace/protobuf/serialization.py, karapace/schema_models.py, karapace/schema_registry_apis.py, mypy.ini, requirements/requirements-typing.in, requirements/requirements-typing.txt, tests/integration/test_schema_protobuf.py, tests/schemas/protobuf.py, tests/unit/test_protobuf_binary_serialization.py
Add support for base64 encoded binary encodings of ProtoBuf schemas when registering new schemas and with format=serialized query parameter when fetching the schemas. Fixes #742 #398
Current implementation uses protobuf python package for binary serialization. On top of that it needs both ways converting between internal protobuf schema presentation and protobuf library definition of types.
=> Support binary serialization of ProtoBuf schemas

karapace/protobuf/enum_element.py, karapace/protobuf/message_element.py, karapace/protobuf/option_element.py, karapace/protobuf/type_element.py, mypy.ini
Fix typing in protobuf enum and message elements
=> Fix typing in protobuf enum and message elements

.github/workflows/lint.yml, .github/workflows/schema.yml, requirements/requirements-dev.txt, requirements/requirements-typing.txt, requirements/requirements.in, requirements/requirements.txt, setup.py, tests/unit/test_features.py
Require kafka codec compression dependencies always instead of optionally, and add unit test to verify the environment.
Fixes: #766
Rationale: those dependencies are not a big addition, but are sometimes critical to get karapace running.
=> Require kafka codec deps always and test feature support

karapace/schema_reader.py
Fix error logging in schema reader that would cause further exceptions.
The `topic` variable is of course nonexistent if the topic creation fails with an exception.
=> Fix logging on failed schema reader topic creation

karapace/schema_models.py, tests/integration/test_schema_protobuf.py
When only updating a reference to a schema a new schema and version is required to be created.
The references are also included in the schema fingerprint.
References: #783
Closes #783
The full protobuf schema requires also the the references. If reference is updated the schema is changed, the actual schema string  may be the same. Th
=> fix: create new schema and version on reference update

karapace/schema_models.py, karapace/schema_registry_apis.py, tests/integration/test_schema_protobuf.py
When schema is queried with schema and references the match must happen on the parsed form and with references matching the version.
Closes #791
References: #791
=> fix: Match schemas by parsed schema object and references when queried

karapace/protobuf/compare_type_lists.py, karapace/protobuf/enum_element.py, tests/integration/test_schema_protobuf.py, tests/unit/protobuf/test_protobuf_compatibility.py
Fix schema compatibility checks if ordering of types is changed. Order of types does not affect semantical compatibility of the schemas.
Fixes #795
=> Fix schema registering with ordering change

karapace/kafka/common.py, karapace/kafka/producer.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/authentication.py, karapace/rapu.py, tests/integration/kafka/test_producer.py, tests/integration/test_rest.py, tests/unit/test_authentication.py
* Create a wrapper around the existing, confluent-kafka based `KafkaProducer` with an async `send` method and a poll-thread to send messages continuously in the background
* Dropping the usage of an SSL context for the async producer, as confluent-kafka has no support for this
* Change the REST web application shutdown hook from `on_cleanup` to `on_shutdown` - this was an existing bug preventing any kind of closing of resources (Kafka clients, consumer manager, etc.) to actually run, further explanation in commit message
* (Mostly) drop-in replacement for existing behaviour
* Following the [confluent-kafka example](https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/asyncio_example.py)
=> Implement async confluent-kafka producer

karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/schema_models.py, karapace/schema_reader.py
Exception level logging should only be used for cases where there's an actual application error, but in many cases was being used for recoverable situations and during normal operations and user errors. The right place to use exception level logging is when the exception is unknown, not just when any Python exception has occurred.
In some situations exceptions were logged before being re-raised, those were demoted to info logs since there's no value in having duplicated logging.
Overall, exception handling is not structured throughout Karapace and we at some point need to do a deep inventory. In many places we catch broad exceptions where we really should not, and this is likely having bad effects on behavior during memory constrained operations and similar.
=> Demote various exception logs to warning and info

karapace/kafka_rest_apis/__init__.py
BrokerResponseErrors include meaningful reason and message (e.g. topic authorization failed), which can be passed to caller of Kafka REST api here, so it is not an error in Karapace, and should not be logged as such.
=> Graceful handling of broker response errors

karapace/protobuf/serialization.py, tests/schemas/protobuf.py, tests/unit/test_protobuf_binary_serialization.py
Fix a bug in _deserialize_field that causes deserialization fail in certain cases, e.g. in the case there's a nested field that is a message or an enum. The issue is that the type is optional if type_name is specified. The code falsely expects type to always be present.
Add test test_protoc_serialized_schema_deserialize to test deserialization of protoc-serialized schemas. Test a few cases that are problematic, e.g. one with an enum and another with a nested message.
Better error handling if type and type_name are missing. Raise InvalidSchema instead of using assert.
It would be possible to do the testing in different ways. 
1. The test would generate using protoc the "protoc" Python module (for each tested schema)
2. The test would use the generated code to serialize the tested schema
3. …
=> protobuf: improve protoc compatibility

karapace/rapu.py
Fix internal server error if request body is non-object
Passing valid JSON such as string or int caused internal server errors, because code assumed to read it as object (dictionary) with fields.
=> Fix internal server error if request body is non-object

karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/authentication.py, tests/unit/test_authentication.py
Since we moved away from kafka-python and aiokafka based clients, there is no need to depend on either library's abstract OAuth token provider mechanism. The confluent-kafka clients take a simple callable for token fetching (pass-through in our case).
Rest of the `aiokafka` related cleanup is in https://github.com/Aiven-Open/karapace/pull/798
=> OAuth token prodiver cleanup

karapace/sentry/sentry_client.py, mypy.ini, requirements/requirements-dev.txt, requirements/requirements-typing.txt, requirements/requirements.in, requirements/requirements.txt, setup.py
Remove `aiokafka` as a dependency and regenerate the requirements files, as well as removing it from the mypy configuration.
`kafka-python` remains, as it is still used in the schema registry's coordinator and for translating error codes to human readable exceptions.
=> Remove aiokafka dependency

karapace/schema_registry.py, karapace/schema_registry_apis.py, karapace/typing.py, tests/integration/test_schema_registry_auth.py, tests/integration/test_schema_registry_mode.py
Add mode GET support to Karapace. The mode is always READWRITE and response contains static `{"mode": "READWRITE"}` mode for global and subject modes.
=> feat: GET /mode and GET /mode/<subject:path> endpoints

karapace/auth.py, karapace/schema_registry_apis.py, tests/unit/test_auth.py
Load the subjects associated with the schema id from in-memory database. This list can be used as source for subjects to match user ACLs.
The ACL authorizator is added which can operate only on the user dictionary and permission list. HTTP authorizer inherits this class and add the file loading and HTTP authorization handling on top. Unit tests for ACL authorizer are added.
Reduces the amount of elements iterated from the in-memory database. The returned amount of data is also greatly reduced when in-memory database collects the subjects with schema id directly instead of filtering in the `_has_subject_with_id` function.
=> refactor: optimize the authorization check for get schema by id

karapace/kafka_rest_apis/consumer_manager.py
Tiny change just moving a list instantiation much closer to where it is actually used, making it easier to see that it is only being populated from a single for loop, and not used earlier in the function.
=> refactor: Move list instantiation to where it is used

karapace/protobuf/compare_result.py, karapace/protobuf/message_element.py, tests/unit/protobuf/test_protobuf_compatibility.py
This PR introduces a new `FIELD_TAG_ALTER` modification in order to recognize tag change of fields.
Changing the tag of a field is not backwards compatible but currently goes unnoticed because fields are compared by tag and not by field name. Because of this compatibility check will only recognize `FIELD_NAME_ALTER` modification which is backward compatible. This PR changes this so that if field name exists in both schemas it will compare the tags and add `FIELD_TAG_ALTER` modification if the tags don't match.
=> protobuf: recognize tag alter modification

karapace/schema_registry_apis.py, tests/integration/test_dependencies_compatibility_protobuf.py
Method subjects_schema_post was using the dependencies of the schema in body to parse all the schemas that are matched. This leads to error if both schemas don't share dependencies.
=> fix: resolving references in subjects_schema_post

karapace/schema_reader.py
It's a valid scenario that a message with `error()` set is consumed, however these are retriable in most cases, thus only logging for now.
Related to https://github.com/Aiven-Open/karapace/issues/812
=> Log message error on schema replay

karapace/kafka/consumer.py
Prompted by a [Sentry error](https://aiven-io.sentry.io/issues/5038513254/?notification_uuid=5af4286d-8395-4692-a22e-bdf20bd306d5&project=1219632&referrer=assigned_activity-email), the issue is "triggered" by [this line in the consumer manager](https://github.com/Aiven-Open/karapace/blob/main/karapace/kafka_rest_apis/consumer_manager.py#L279).
The confluent-kafka `Consumer.commit` method can be called with no parameters, then the current partition assignment's offsets are used (see the documentation at
https://docs.confluent.io/platform/current/clients/confluent-kafka-python/html/index.html#confluent_kafka.Consumer.commit).
The previous behaviour was erroneous, raising a `TypeError`, thus an HTTP 500 when in the REST proxy's consumer manager a commit is performed with an empty payload.
=> Fix no-payload commit in consumer

karapace/in_memory_database.py, tests/unit/test_in_memory_database.py
This PR fixes an `IndexError: list index out of range` exception raised when calling `InMemoryDatabase.find_schemas` with argument `latest_only = True` and there's a schema with no versions.
=> fix: handle InMemoryDatabase find_schemas latest when no versions available for subject

tests/integration/kafka/test_consumer.py, tests/integration/test_rest_consumer.py, tests/utils.py
Following up on #833, adding tests around the fix that was hastily implemented there.
=> Add tests for empty payload consumer commit

karapace/schema_registry_apis.py, tests/integration/test_schema.py
When a user sends a bad schema, we return a 500 even though the error is handled.
Here we return a 422 instead.
=> 422 instead of 500 on subject schema error

karapace/schema_reader.py
If leader for partition is not available, it is a temporary error that is resolved after re-fetching metadata.  Log, but ignore those errors.
These both errors are documented as temporary.
=> Retry on temporary errors from schema reader

README.rst, karapace/kafka_rest_apis/consumer_manager.py, karapace/protobuf/compare_type_lists.py, karapace/protobuf/enum_element.py, karapace/protobuf/extend_element.py, karapace/protobuf/group_element.py, karapace/protobuf/message_element.py, karapace/protobuf/one_of_element.py, karapace/protobuf/option_element.py, karapace/protobuf/proto_file_element.py, karapace/protobuf/proto_normalizations.py, karapace/protobuf/serialization.py, karapace/protobuf/service_element.py, karapace/protobuf/type_element.py, karapace/schema_models.py, karapace/schema_reader.py, karapace/schema_registry_apis.py, tests/integration/test_schema_protobuf.py, tests/unit/protobuf/test_protobuf_normalization.py
The options could be of different types:
1. string
2. boolean
3. number
4. enum
5. map
6. list
7. option
Here I've added an example for each one of them:
1. STRING:
```
option example_option = "hello world";
```
2. BOOLEAN:
```
option example_option = true;
```
3. NUMBER:
```
option example_option = 42;
```
4. ENUM:
```
enum ExampleEnum {
OPTION_ONE = 1;
OPTION_TWO = 2;
}
option example_option = OPTION_ONE;
```
5. MAP:
```
message ExampleMessage {
map<string, int32> example_map = 1;
}
option (map_option) = {
key: "key1"
value: 42
};
```
6. LIST:
```
message ExampleMessage {
repeated string example_list = 1;
}
option (list_option) = [
"item1",
"item2",
"item3"
];
```
7. OPTION:
```
option (custom_option) = {
string_option: "hello world",
enum_option: OPTION_ONE,
boolean_option: true
};
``` …
=> normalization: add normalization of the options

karapace/schema_registry_apis.py, tests/integration/test_schema.py
Fix formatting of error message variable expansion if subject level compatibility mode is not configured.
Old code was literally asserting that error message was `Subject '%s' does not have subject-level compatibility configured`
=> Fix error message formatting variable expansion

karapace/kafka_rest_apis/__init__.py, tests/integration/test_rest.py
Karapace returned 500 error for JSON payload that did not match JSON schema when serialization format was `jsonschema`.
Added an integration test which tests also Avro schema and payload.
=> fix: return 422 for Avro/JSONSchema when payload does not match schema

README.rst
Set the correct repository links after the repository has been moved from @aiven to @aiven-open
References: None
Avoiding redirects or broken images (e.g. when image redirects not work)
=> README: Fix badge for workflow run of `tests.yml`

karapace/rapu.py, tests/unit/test_rapu.py
If client connection is broken there is nothing the server can do. Handle the specific case and silence stats and reporting. The aiohttp expects a response object, although this is not and cannot be written to client as the connection is already broken.
=> fix: handle ConnectionError in rapu._handle_messages

karapace/serialization.py, tests/unit/test_serialization.py
avro arrays and maps have no name property. Instead type property is used as name.
=> fix: flatten_unions for array and map union types

.github/workflows/tests.yml, requirements/requirements-dev.in, requirements/requirements-dev.txt, tests/integration/test_rest_consumer.py, tests/unit/test_schema_registry_api.py
Run tests in a random order.
Reproduce rest consumer failure in random order: `--random-order-bucket=global --random-order-seed=472073` (with process number 2)
Reproduce unittest failure in random order: `--random-order --random-order-seed=275491` (bucket is default `module`)
=> Randomize test run order

GNUmakefile
In eb9ee31b3ff5879546d70737903cd6941562fb2d, pip-compile was changed to no longer cd into the requirements directory. The reason for this change was because of the use of `ONESHELL` which causes diverging behavior in environments with make versions that don't yet support this mode.
This commit reverts the removal of the `cd` invocations, and additionally removes the `ONESHELL` option which should make behavior aligned across dev envs.
=> fix: Restore pip-compile invocation

requirements/requirements-dev.txt, requirements/requirements-typing.txt, requirements/requirements.in, requirements/requirements.txt
Update `kafka-python` with vendored `six==1.16.0`. This enables update of `pytest` to `8.x`.
=> chore: update kafka-python with vendored six 1.16.0

karapace/schema_reader.py, tests/unit/test_schema_reader.py
If Karapace would expect to consume multiple records after startup, there is extra latency of the consumption timeout as consumer does not return control back to schema reader until it happens. This would cause extra latency when storing schema.
On normal operating mode after startup there expectation is to process single record at a time and return control immediately to schema reader when record is available.
=> fix: consume only one record at a time after startup

karapace/protobuf/option_element.py, tests/unit/test_protobuf_binary_serialization.py
The protobuf rendering did not change the boolean value to lowercase as expected in the IDL file.
=> Fix java multiple files protobuf option rendering

karapace/kafka_rest_apis/__init__.py, tests/unit/kafka_rest_apis/test_rest_proxy_cache.py, tests/unit/kafka_rest_apis/test_rest_proxy_cluster_metadata_cache.py
the cache each time was replacing the original metadata even if the metadata request was just for a subset of topics, this pr tries to address this by updating only partially the metadata object
=> fix cache: the cache metadata its always replaced even if its only updating a subportion of it

karapace/backup/api.py, karapace/backup/cli.py, karapace/coordinator/schema_coordinator.py, karapace/kafka/common.py, karapace/kafka/consumer.py, karapace/kafka_rest_apis/__init__.py, karapace/kafka_rest_apis/consumer_manager.py, karapace/messaging.py, karapace/schema_reader.py, karapace/utils.py, requirements/requirements-dev.txt, requirements/requirements.in, requirements/requirements.txt, setup.py, tests/integration/backup/test_legacy_backup.py, tests/integration/backup/test_v3_backup.py, tests/integration/kafka/test_admin.py, tests/integration/kafka/test_consumer.py, tests/integration/kafka/test_producer.py, tests/integration/utils/kafka_server.py, tests/unit/backup/test_api.py, tests/unit/test_features.py, tests/utils.py
Remove `kafka-python` dependency. Error that were mapped from `kafka-python` are now mapped to `aiokafka` which will be a dependency through the schema coordinator.
=> chore: remove kafka-python dependency

karapace/schema_reader.py, tests/unit/test_schema_reader.py
Move the offset in schema reader also when the record key or value is not valid JSON.
The reading can get stuck as offset is not moved.
=> fix: move offset always, also with invalid processed records

karapace/dependency.py, karapace/in_memory_database.py, karapace/schema_reader.py, karapace/schema_references.py, karapace/schema_registry.py, karapace/schema_registry_apis.py, karapace/typing.py, tests/unit/test_schema_models.py
Make Version a container class for integer for stronger typing.
=> refactor: remove int inheritance from Version

tests/integration/test_schema.py
=> test: add JSON schema test to schema in multiple subjects test

tests/unit/test_schema_reader.py
When _schemas topic has been compacted and only soft deleted version of the schema is present the schema must be stored in the in memory database.
Fixes #170.
=> test: store soft deleted schema

karapace/rapu.py, tests/unit/test_rapu.py
This catches `aiohttp.ClientError` and returns `HTTPStatus<503>` rather than `HTTPStatus<500>`. 
We also catch the base `aiohttp.ClientError` rather than just `aiohttp.ClientConnectorError`, as for us, most client errors will also be TCP connection related, rather than actual invalid request data, etc and we include the exception information with the logged message, this can further aid debugging. 
References: [HH-3866](https://aiven.atlassian.net/browse/HH-3866)
Reflects properly the behaviour of the server via the response status.
=> rapu: catch `aiohttp.ClientError` with a `503` response status

tests/integration/conftest.py, tests/integration/kafka/test_consumer.py
Consumer close can get stuck if the referenced topic is deleted from broker before.
=> Fix fixture order for consumer tests

.coveragerc, .github/workflows/tests.yml, requirements/requirements-dev.in, requirements/requirements-dev.txt
=> chore: add coverage report

container/compose.yml, container/prometheus.yml, karapace/client.py, karapace/instrumentation/prometheus.py, karapace/karapace_all.py, requirements/requirements-dev.txt, requirements/requirements.in, requirements/requirements.txt, tests/integration/instrumentation/test_prometheus.py, tests/unit/instrumentation/test_prometheus.py
Add Observability to the Karapace services (`registry`, `rest`) via prometheus metrics and instrumentation.
Using prometheus, we can take advantage of it's labels, dimensional data model, available tools and ecosystem. This provides the building blocks of adding observability into the service, with focus on extensibility and testing (unit and integration).
- Right now, we have added a few metric types majorly for the HTTP requests, but this can be extended with more metrics for the different operations of the system, i.e. `schema reader` metrics, etc.
- We use the `karapace` prefix to act as a namespace and identifier for the service metrics.
- A sample prometheus service is added to the docker compose setup to show the pulled metrics via the `prometheus.scrape_configs`, the UI is shown …
=> feature, observability: Added Prometheus Metrics & Instrumentation

karapace/rapu.py
Handle `asyncio.TimeoutError`.
- we also prevent reraising `asyncio.CanclledError` as it is not necessary within this context, this could cause the app to crash or other unexpected behaviour.
=> chore, rapu: handle `asyncio.TimeoutError`

karapace/typing.py, tests/unit/test_schema_models.py
… This is required due to back compatibility, in the past was possible to create schema with version 0, we should deny creating new versions starting from 0 but not raising an issue if this is done during the load of the previous schema
=> fix: remove the raise Invalid version when instantiating a version 0

karapace/protobuf/proto_normalizations.py, karapace/protobuf/schema.py, karapace/protobuf/type_tree.py, karapace/schema_models.py, karapace/utils.py, tests/unit/protobuf/test_protobuf_normalization.py, tests/unit/test_utils.py
This is not complete normalization feature but rather more a fix for the fully qualified paths vs simple name references. This fix not manage the various way a type can be expressed with a partial path.
Long explanation below:
If we accept the specifications from buf as correct, we can look at how a type reference is defined [here](https://protobuf.com/docs/language-spec#type-references).
The main problem with the previous implementation is that the current parser can't tell if a fully-qualified type reference in dot notation is the same as one identified by name alone aka simple name notation ([fully qualified reference](https://protobuf.com/docs/language-spec#fully-qualified-references)).
The fix do not consider all the different ways users can define a relative reference, schemas
with …
=> fix: get rid of the path for fully qualified names.

karapace/coordinator/schema_coordinator.py
The logs changed are warnings, the coordinator should correct the issue.
=> fix: change schema coordinator error logs to warning

karapace/protobuf/io.py
If base exception is raised the communication queue will block in the calling process and will cause timeouts. This is prevalent in unit test for protobuf serialization in Github Actions, caused by the protobuf compiler work directory existence. The fix is to use pathlib.Path with exists=True and parents=True for removing the FileExistsError and also changing the error handling logic to pass back also BaseExceptions through the multiprocess queue.
=> fix: catch all exceptions in forked process

.github/workflows/lint.yml, .github/workflows/schema.yml, .github/workflows/tests.yml, .pre-commit-config.yaml, .pylintrc, karapace/backup/api.py, karapace/backup/backends/v2.py, karapace/backup/safe_writer.py, karapace/protobuf/known_dependency.py, karapace/protobuf/message_element.py, karapace/protobuf/proto_type.py, karapace/protobuf/syntax_reader.py, karapace/schema_registry.py, karapace/utils.py
=> chore: update for Python 3.12

karapace/schema_reader.py, tests/unit/test_schema_reader.py
We use the repr `%r` formatting instead of int `%d` for the affected log line and add a test to catch this and act as a reference for testing log statements. 
```
TypeError: %d format: a real number is required, not Version')
```
=> fix: `Version` int log formatting in `schema_reader.py`

karapace/schema_registry_apis.py, karapace/typing.py, tests/integration/schema_registry/test_jsonschema.py, tests/integration/test_schema_protobuf.py, tests/unit/test_schema_registry_api.py
Allow definition of two new fields when schema is registered to keep compatibility with confluent clients
[Issue Number 916](https://github.com/Aiven-Open/karapace/issues/916)
See: https://docs.confluent.io/platform/current/schema-registry/develop/api.html#post--subjects-(string-%20subject)
=> chore: confluent API spec evolution

container/compose.yml, container/grafana/dashboards/karapace.json, container/grafana/provisioning/dashboards/default.yaml, container/grafana/provisioning/datasources/default.yaml, container/prometheus/prometheus.yml, container/prometheus/rules.yml, karapace/config.py, karapace/statsd.py
This PR adds a `statsd-exporter` to the service, which will translate existing statsd metrics in influxdb style to prometheus metrics. We also add a simple grafana dashboard to Karapace, thus we can visualize the various metrics. 
We also now take the statsd host and port values from the config/env, rather than being hard coded within the client.
Sample prometheus `rules` file was added and a calculated metric is used within the dashboard. Spin up the container, send some requests and see the metrics on grafana and see the firing alerts on the prometheus alert manager. 
Alerts firing from the prometheus `rules` file, added with a low threshold so we see it fire:
This is not final, the recorded metrics could use better promql techniques, this is just a base for any future work and at least …
=> metrics, visualization: StatsD Exporter, Prometheus Rules & Grafana Dashboard

karapace/rapu.py, tests/unit/test_rapu.py
- we add the `karapace_shutdown_count` metric, to the base app and fire the metric on app shutdown
- the `close_by_app()` is added to the app shutdown hooks and thus is called on app shutdown
This way we have a metric to count the app shutdown ands this is handled on the app server level, rather than in application code.
=> rapu: fire shutdown metric on app shutdown

karapace/protobuf/exception.py, karapace/schema_reader.py, tests/unit/test_schema_reader.py, tests/utils.py
We add tests to validate the possible error cases while parsing the message key:
- we test for invalid JSON for key
- missing `keytype` in the key data
- we test for invalid `keytype`
- we test for invalid config value
- we test for invalid subject delete value
- we test for invalid version number within schema value
- we test for generic invalid protobuf schema
This is not added via the integration tests as we are verifying the side-effects which are then handled by other components and thus the unit tests are fine just to add. 
The work requires the work currently done in #936 and thus was tested locally with a rebase on that branch, some linting and added tests might fail until we merge the other PR.
=> tests,schema_reader: kafka message handling error tests

tests/integration/conftest.py, tests/integration/test_master_coordinator.py, tests/integration/test_schema_registry_auth.py, tests/integration/utils/rest_client.py
=> chore: add retry to tests requiring forwarding

.github/workflows/tests.yml
Use 4 workers in GH actions. Default or `--numprocesses auto` does not use the 4 vcpus available on the Github runner.
The number of vcpus has been changed in the GH runners: https://github.blog/news-insights/product-news/github-hosted-runners-double-the-power-for-open-source/
=> chore: add --numprocesses to GH action pytest args

tests/integration/backup/test_session_timeout.py, tests/integration/conftest.py, tests/integration/test_karapace.py, tests/integration/test_master_coordinator.py, tests/integration/utils/cluster.py, tests/integration/utils/network.py
The previous port selection algorithm relied on port range. The range
was from 48700 to 49000. This is 300 ports of which some may be already
reserved in the system running tests. The free ports are allocated between
the pytest workers. With 4 workers there is 75 ports for each. This causes
flakiness in the tests as ports may not be available or are still in
wait after previous tests. In the test environment it is not necessary
to select ports from IANA dynamic port assignment range. Any free port
is ok and port 0 can be used for dynamically allocated free port.
=> test: select random free server ports with 0

tests/unit/test_schema_reader.py, tests/utils.py
Given a valid schema, if it references an invalid (corrupted) schema then:
- Exception CorruptKafkaRecordException should be raised
- Warning Invalid Protobuf references should be logged
=> tests, protobuf: add test on invalid reference schema

karapace/schema_reader.py, tests/unit/test_schema_reader.py
- we add the kafka message key to the log in the case of an error, this makes it easier to debug issues
- we also add a check for kafka messages without a key
=> schema-reader: Log the erroring kafka message key

src/karapace/backup/backends/v3/schema_tool.py, src/karapace/kafka/common.py, src/karapace/schema_reader.py, stubs/confluent_kafka/cimpl.pyi
translates [_RESOLVE](https://docs.confluent.io/platform/current/clients/librdkafka/html/rdkafkacpp_8h.html#a4c6b7af48c215724c323c60ea4080dbfa4a4c3916fd4d99d59c5bc29a6d39ee4b) error code to KafkaUnavailableError. Also don't log KafkaUnavailableError as unexpected error.
Also fixes check for new project source layout in `schema_tool.py`
=> fix: unknown Kafka errors with _RESOLVE error code

MANIFEST.in
=> fix: add Protopace go source to be included in MANIFEST.in

tests/conftest.py, tests/integration/conftest.py
=> chore: update tests to use Kafka 3.4.1

src/karapace/karapace.py, src/karapace/schema_reader.py, src/karapace/schema_registry_apis.py, stubs/confluent_kafka/__init__.pyi, stubs/confluent_kafka/admin/__init__.pyi, stubs/confluent_kafka/cimpl.pyi, tests/integration/test_health_check.py, tests/unit/test_schema_reader.py
This PR improves the health check endpoint by returning 503 if the schema_reader throws  >= 3 unexpected consecutive exceptions in 10 seconds.
In addition it will check if topic is available on the kafka cluster.  This is needed because consumer will only return error once in this case.
In its current state health check would always report healthy service even if connection to kafka was broken.
=> feat: improve health check to fail if schema_reader raises exceptions

src/karapace/avro_dataclasses/introspect.py
=> fix: Avro dataclass introspect typing

src/karapace/schema_registry_apis.py, tests/integration/test_schema.py, tests/integration/test_schema_compatibility.py
For Confluent Schema Registry client compatibility the response field is changed from "incompatibilities: str" to "messages: list[str]".
=> fix: return "messages" instead "incompatibilities" from compatibility API

src/karapace/backup/backends/v3/schema_tool.py
=> chore: remove schema tool source layout check

src/karapace/kafka_rest_apis/consumer_manager.py, tests/integration/test_rest_consumer.py
=> fix: validate REST Proxy subscription param types

tests/integration/backup/test_v3_backup.py
Using some (old) fixed timestamps when producing messages was causing the
messages to be automatically deleted because past message retention.
I think most of the time the test was managing to complete successfully
before the retention kicked in, making it fail only sometimes.
=> tests,backup: fix flakiness by using current timestamps

src/karapace/protobuf/serialization.py, tests/schemas/protobuf.py, tests/unit/test_protobuf_binary_serialization.py
This fixes  deserialization of optionals in proto3 descriptors as they are represented by synthetic oneofs.
=> fix: proto3 optionals from base64 encoded proto descriptors

src/karapace/backup/api.py, src/karapace/backup/cli.py, tests/integration/backup/test_v3_backup.py
This flag is useful if you created a backup of a cluster with N nodes, and now you want to restore on a cluster with less than N  nodes.
Also take a look at: https://github.com/aiven/backups-for-apache-kafka/pull/51
=> backup: add command line flag to override replication factor in restore command

src/karapace/sentry/sentry_client.py
These log events are numerous and costly. When these `log.error` events are related to real error, they cause exceptions which are still properly handled and recorded by Sentry, no need to also send individual events for all the `log.error` in addition to the exceptions. 
The same logic was already applied for the `kafka` library.
=> fix: don't send all aiokafka log.error to sentry

src/karapace/key_format.py, src/karapace/schema_registry_apis.py
Previously we were relying on the fact that the `.keys()` order and the `json.dumps()` order are always sync. This enforces by the `OrderedDict` a fixed order. Not sure if the same odering check should be performed also for the `is_key_in_canonical_format`, probably here we want to ensure that the current dict has exactly the same order in the `keys()`.
=> fix: harden the order of keys that needs to be serialized

README.rst, src/karapace/config.py, src/karapace/coordinator/master_coordinator.py, src/karapace/coordinator/schema_coordinator.py, src/karapace/schema_reader.py, src/karapace/schema_registry.py, src/karapace/schema_registry_apis.py, src/karapace/typing.py, tests/integration/conftest.py, tests/integration/test_master_coordinator.py, tests/integration/test_schema_coordinator.py, tests/integration/test_schema_reader.py, tests/unit/test_schema_reader.py, tests/unit/test_schema_registry_api.py, tests/utils.py
coordinator rewrite
1. moving the coordinator in a separate thread
2. adding a waiting time between when the master its elected and the master can act. This has been done to avoid rapid elections of master that may produce schemas with different ids.
Example of what could happpen without the delay:
```md
|--------------------------------------|
|Node | Node1    | Node2    | Node3    |
|Role | Master   | Follower | Follower |
|--------------------------------------|
Node1 -> Send Message A{id=max(current_ids)} to kafka
where the max(current_ids) = 10
---------------------------------------
Node1 its disconnected, the message its still in the producer queue of Node1
---------------------------------------
Node2 its elected master
|--------------------------------------|
|Node | Node1    | …
```
=> fix: duplicated schemas on rapid elections while continuous produce of records

.github/workflows/container.yml
=> fix: add the context output back to container GH Action workflow

container/Dockerfile
About this change - What it does
This change updates the Dockerfile to handle dynamic User ID (UID) allocation in compliance with OpenShift best practices. It modifies file and directory permissions to ensure compatibility with OpenShift's security requirements, allowing containers to run with arbitrary UIDs while maintaining the required access to essential directories.
References: #983 
Why this way
To solve the issue of dynamic UID handling, the proposed approach involves modifying permissions so that the container user can run with a dynamically assigned UID, which OpenShift uses for security purposes. Specifically, we change directory permissions and add the 'karapace' user to group '0', ensuring necessary access without granting root privileges. This adheres to OpenShift's …
=> feat: Update Dockerfile to add support to arbitrary user ids

src/karapace/config.py
The StatsD client is created if there is non-null host defined. The default is required to be None so the client won't get created.
=> fix: StatsD host default required to be None

mypy.ini, src/karapace/auth.py, src/karapace/config.py, src/karapace/forward_client.py, src/karapace/rapu.py, src/karapace/statsd.py, src/karapace/typing.py, src/schema_registry/factory.py, src/schema_registry/http_handlers/__init__.py, src/schema_registry/middlewares/__init__.py, src/schema_registry/routers/config.py, src/schema_registry/routers/master_availability.py, src/schema_registry/routers/metrics.py, src/schema_registry/routers/mode.py, src/schema_registry/routers/schemas.py, src/schema_registry/routers/subjects.py, src/schema_registry/schema_registry_apis.py, src/schema_registry/user.py, tests/integration/test_master_coordinator.py, tests/integration/test_schema_registry_auth.py, tests/integration/utils/cluster.py, tests/unit/test_forwarding_client.py
=> Linting fixes

.dockerignore, .github/workflows/container-smoke-test.yml, .github/workflows/lint.yml, .github/workflows/tests.yml, GNUmakefile, container/Dockerfile.dev, container/compose.yml, mypy.ini, pyproject.toml, src/karapace/kafka/consumer.py, src/karapace/schema_reader.py
Now with the tests running in docker, we add the support to run with multiple python version provided by the github actions matrix. 
**I suspect that we will have issues with python3.9,** a local stacktrace of a startup error faced on python3.9 can be seen below:
```shell
ImportError while loading conftest '/opt/karapace/tests/conftest.py'.
tests/conftest.py:6: in <module>
from karapace.container import KarapaceContainer
src/karapace/container.py:7: in <module>
from karapace.auth import get_authorizer, HTTPAuthorizer, NoAuthAndAuthz
src/karapace/auth.py:11: in <module>
from karapace.config import Config, InvalidConfiguration
src/karapace/config.py:30: in <module>
class Config(BaseSettings):
venv/lib/python3.9/site-packages/pydantic/_internal/_model_construction.py:221: in __new__ …
```
=> ci: multi-python version docker image for GHA matrix

GNUmakefile, src/karapace/forward_client.py, src/schema_registry/factory.py, tests/unit/test_forwarding_client.py
We use a single client session for the forwarded requests and further close the session on application shutdown.
=> forwarding_client: use single session and close on shutdown

src/schema_registry/routers/errors.py, tests/e2e/schema_registry/test_jsonschema.py, tests/integration/test_schema_protobuf.py
=> fix: schema error codes required to be json serializable

src/karapace/config.py
=> chore: resolve otel version from import

src/karapace/config.py, src/schema_registry/telemetry/middleware.py, src/schema_registry/telemetry/tracer.py, tests/unit/schema_registry/telemetry/test_middleware.py, tests/unit/schema_registry/telemetry/test_tracer.py
=> fix: use server host and port instead of host header values

src/karapace/config.py, src/karapace/karapace_all.py, src/karapace/rapu.py, tests/unit/test_config.py
=> fix: max http request size for Karapace REST

src/karapace/config.py, src/karapace/coordinator/master_coordinator.py, src/karapace/coordinator/schema_coordinator.py, src/karapace/rapu.py, src/karapace/typing.py, src/schema_registry/controller.py, src/schema_registry/factory.py, src/schema_registry/reader.py, src/schema_registry/registry.py, src/schema_registry/routers/config.py, src/schema_registry/routers/master_availability.py, src/schema_registry/routers/subjects.py, tests/integration/conftest.py, tests/integration/test_master_coordinator.py, tests/integration/test_request_forwarding.py, tests/integration/test_schema_protobuf.py, tests/integration/test_schema_reader.py, tests/integration/utils/cluster.py, tests/unit/schema_registry/test_forwarding.py, tests/utils.py
=> fix: no forwarding if primary url own

.github/workflows/tests.yml
We try to speed up the tests by caching the docker layer.
=> gha: use docker layer cache for tests

src/karapace/backup/cli.py, tests/integration/backup/test_v3_backup.py
The config for backup tool is still the full Karapace config. Config for Karapace is a set of environment variables opposed to prior JSON file. Backup tool will still use the JSON format.
=> fix: backup tool shall still use the JSON config file

container/compose.yml, container/opentelemetry/collector-config.yaml, container/prometheus/prometheus.yml, src/karapace/config.py, src/schema_registry/__main__.py, src/schema_registry/factory.py, src/schema_registry/telemetry/container.py, src/schema_registry/telemetry/meter.py, src/schema_registry/telemetry/metrics.py, src/schema_registry/telemetry/middleware.py, src/schema_registry/telemetry/setup.py, tests/conftest.py, tests/unit/schema_registry/telemetry/test_meter.py, tests/unit/schema_registry/telemetry/test_metrics.py, tests/unit/schema_registry/telemetry/test_middleware.py
- we add OTel metering and HTTP metrics to the service.
- the metrics are exported to `prometheus` via the `opentelemetry-collector` as shown below
- no changes to  the `grafana` dashboard shows that the `prometheus` source still works as expected
- update the `schema_reader` metrics to use the OTel meter
- maybe deprecate `statsd`
- close the prometheus PR #1007 as we now use the OTel metering and exporting to prometheus, thus native prometheus instrumentation is not needed
=> feat: OTel metrics & metering

src/karapace/client.py, src/schema_registry/routers/compatibility.py, src/schema_registry/routers/config.py, src/schema_registry/routers/mode.py, src/schema_registry/routers/raw_path_router.py, src/schema_registry/routers/subjects.py, tests/integration/test_dependencies_compatibility_protobuf.py, tests/integration/test_request_forwarding.py, tests/integration/test_schema.py, tests/integration/test_schema_protobuf.py, tests/integration/test_schema_registry_mode.py, tests/utils.py
Adds support for url encoded forward slashes in subject names.
See: https://github.com/encode/starlette/issues/826
See: https://github.com/fastapi/fastapi/discussions/7328#discussioncomment-8443865
=> feat: handle urlencoded forward slash in subject

src/schema_registry/telemetry/middleware.py, tests/unit/schema_registry/telemetry/test_middleware.py
=> fix: re-raise exception in telemetry middleware

pyproject.toml, requirements/requirements-dev.txt, requirements/requirements-typing.txt, requirements/requirements.txt, src/karapace/serialization.py, tests/integration/test_client_protobuf.py
lru_cache does not work with async functions
=> fix: use async lru_cache

tests/integration/backup/test_session_timeout.py
There is a test which uses producer instead of consumer to test session.timeout.ms (consumer config).
This PR updates it
=> Updating session timeout tests

src/karapace/kafka_rest_apis/consumer_manager.py, tests/integration/kafka_rest_apis/test_rest_consumer.py
When committing a consumer offset via karapace `/offsets` without having consumed a message, the rest proxy returns 
{"error_code":500,"message":"error sending commit request: [Error -1] UnknownError"}
This is now fixed, to return a success response, as it is safe to return 200.
=> Consumer commit fix

pyproject.toml, src/karapace/kafka_rest_apis/__main__.py
Fix entrypoints of Karapace in pyproject.toml.
=> fix: fix script entrypoints

src/karapace/api/middlewares/__init__.py, src/karapace/api/oidc/middleware.py, src/karapace/core/config.py, tests/unit/test_oidc.py
- Ability to authorize karapace schema registry requests based on oidc roles
New example configs in karapace config
```
sasl_oauthbearer_jwks_endpoint_url: str = "http://localhost:8080/realms/klaw/protocol/openid-connect/certs"
sasl_oauthbearer_expected_issuer: str = "http://localhost:8080/realms/klaw"
sasl_oauthbearer_expected_audience: str = "account"
sasl_oauthbearer_sub_claim_name: str | None = "sub"
sasl_oauthbearer_authorization_enabled: bool = True
sasl_oauthbearer_client_id: str = "klaw"
sasl_oauthbearer_roles_claim_path: str = "resource_access.[client_id].roles"
sasl_oauthbearer_method_roles: dict[str, list[str]] = {"GET": ["schema:read", "subject:read"],
"POST": [], "PUT": [], "DELETE": []}
```
Authorization for GET/POST/PUT/DELETE
=> OIDC karapace authorization

container/compose.yml
Adds kafka-3.9 to docker compose:
- drop zookeeper for kafka running in KRaft mode.
- adds meaningful `hostname` and `container_name` to services rather than the auto-generated naming.
- use specific karapace network and bridge driver so we can connect to the compose resources via services maybe in another compose setup by referencing the same network.
=> docker: use kafka-3.9

src/karapace/api/routers/health.py, tests/integration/test_health_check.py
Schema Registry API lib changed from aiohttp to fastapi with Karapace v5. Following to that, the api endpoint `_health` was missing `karapace_version`.
v4 /_health response:
```
{
"process_uptime_sec": 265,
"karapace_version": "4.1.2",
...
}
```
v5 /_health response (before this change)
```
{
"status": {
"schema_registry_ready": true,
"schema_registry_startup_time_sec": 0.255569011999796,
...
}
}
```
v5 /_health response (aftter this change)
```
{
"karapace_version":"5.0.1.dev16+gf199ad007.d20250818",
"status": {
"schema_registry_ready": true,
"schema_registry_startup_time_sec": 8.353399749998061,
...
}
}
```
=> feat: re-add `karapace_version` to sr api endpoint `_health`

src/karapace/core/config.py
If producer_acks is set to all, sometimes it fails in integer parsing.
_producer_acks :   Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='all', input_type=str]_
It is now being fixed in config with this decorator.
=> Fix producer acks
